# copyright - metaengineeringconsultants@gmail.com
# abaqus 2017 compatibility 
# bending of stud
# input data
from abaqus import *
from abaqusConstants import *
import __main__

def Macro5():
    import section
    import regionToolset
    import displayGroupMdbToolset as dgm
    import part
    import material
    import assembly
    import step
    import interaction
    import load
    import mesh
    import optimization
    import job
    import sketch
    import visualization
    import xyPlot
    import displayGroupOdbToolset as dgo
    import connectorBehavior
s = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=100.0)
g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints
s.setPrimaryObject(option=STANDALONE)
s.Line(point1=(11, 1),point2=(11, 2))
s.Line(point1=(11, 2),point2=(11, 3))
s.Line(point1=(11, 3),point2=(11, 4))
s.Line(point1=(11, 4),point2=(11, 5))
s.Line(point1=(11, 5),point2=(10, 6))
s.Line(point1=(10, 6),point2=(10, 7))
s.Line(point1=(10, 7),point2=(9, 8))
s.Line(point1=(9, 8),point2=(8, 9))
s.Line(point1=(8, 9),point2=(7, 9))
s.Line(point1=(7, 9),point2=(6, 9))
s.Line(point1=(6, 9),point2=(5, 9))
s.Line(point1=(5, 9),point2=(4, 9))
s.Line(point1=(4, 9),point2=(3, 10))
s.Line(point1=(3, 10),point2=(2, 10))
s.Line(point1=(2, 10),point2=(1, 10))
s.Line(point1=(1, 10),point2=(1, 11))
s.Line(point1=(1, 11),point2=(1, 12))
s.Line(point1=(1, 12),point2=(1, 13))
s.Line(point1=(1, 13),point2=(1, 14))
s.Line(point1=(1, 14),point2=(1, 15))
s.Line(point1=(1, 15),point2=(1, 16))
s.Line(point1=(1, 16),point2=(1, 17))
s.Line(point1=(1, 17),point2=(1, 18))
s.Line(point1=(1, 18),point2=(1, 19))
s.Line(point1=(1, 19),point2=(1, 20))
s.Line(point1=(1, 20),point2=(1, 21))
s.Line(point1=(1, 21),point2=(1, 22))
s.Line(point1=(1, 22),point2=(1, 23))
s.Line(point1=(1, 23),point2=(1, 24))
s.Line(point1=(1, 24),point2=(1, 25))
s.Line(point1=(1, 25),point2=(1, 26))
s.Line(point1=(1, 26),point2=(1, 27))
s.Line(point1=(1, 27),point2=(1, 28))
s.Line(point1=(1, 28),point2=(1, 29))
s.Line(point1=(1, 29),point2=(1, 30))
s.Line(point1=(1, 30),point2=(1, 31))
s.Line(point1=(1, 31),point2=(1, 32))
s.Line(point1=(1, 32),point2=(1, 33))
s.Line(point1=(1, 33),point2=(1, 34))
s.Line(point1=(1, 34),point2=(1, 35))
s.Line(point1=(1, 35),point2=(1, 36))
s.Line(point1=(1, 36),point2=(1, 37))
s.Line(point1=(1, 37),point2=(1, 38))
s.Line(point1=(1, 38),point2=(1, 39))
s.Line(point1=(1, 39),point2=(1, 40))
s.Line(point1=(1, 40),point2=(1, 41))
s.Line(point1=(1, 41),point2=(2, 41))
s.Line(point1=(2, 41),point2=(3, 41))
s.Line(point1=(3, 41),point2=(4, 42))
s.Line(point1=(4, 42),point2=(5, 42))
s.Line(point1=(5, 42),point2=(6, 42))
s.Line(point1=(6, 42),point2=(7, 42))
s.Line(point1=(7, 42),point2=(8, 42))
s.Line(point1=(8, 42),point2=(9, 43))
s.Line(point1=(9, 43),point2=(10, 44))
s.Line(point1=(10, 44),point2=(10, 45))
s.Line(point1=(10, 45),point2=(11, 46))
s.Line(point1=(11, 46),point2=(11, 47))
s.Line(point1=(11, 47),point2=(11, 48))
s.Line(point1=(11, 48),point2=(11, 49))
s.Line(point1=(11, 49),point2=(11, 50))
s.Line(point1=(11, 50),point2=(12, 50))
s.Line(point1=(12, 50),point2=(13, 50))
s.Line(point1=(13, 50),point2=(14, 50))
s.Line(point1=(14, 50),point2=(15, 50))
s.Line(point1=(15, 50),point2=(16, 50))
s.Line(point1=(16, 50),point2=(17, 50))
s.Line(point1=(17, 50),point2=(18, 50))
s.Line(point1=(18, 50),point2=(19, 50))
s.Line(point1=(19, 50),point2=(20, 50))
s.Line(point1=(20, 50),point2=(21, 50))
s.Line(point1=(21, 50),point2=(22, 50))
s.Line(point1=(22, 50),point2=(23, 50))
s.Line(point1=(23, 50),point2=(24, 50))
s.Line(point1=(24, 50),point2=(25, 50))
s.Line(point1=(25, 50),point2=(26, 50))
s.Line(point1=(26, 50),point2=(27, 50))
s.Line(point1=(27, 50),point2=(28, 50))
s.Line(point1=(28, 50),point2=(29, 50))
s.Line(point1=(29, 50),point2=(30, 50))
s.Line(point1=(30, 50),point2=(31, 50))
s.Line(point1=(31, 50),point2=(32, 50))
s.Line(point1=(32, 50),point2=(33, 50))
s.Line(point1=(33, 50),point2=(34, 50))
s.Line(point1=(34, 50),point2=(35, 50))
s.Line(point1=(35, 50),point2=(36, 50))
s.Line(point1=(36, 50),point2=(37, 50))
s.Line(point1=(37, 50),point2=(38, 50))
s.Line(point1=(38, 50),point2=(39, 50))
s.Line(point1=(39, 50),point2=(40, 50))
s.Line(point1=(40, 50),point2=(40, 49))
s.Line(point1=(40, 49),point2=(40, 48))
s.Line(point1=(40, 48),point2=(40, 47))
s.Line(point1=(40, 47),point2=(40, 46))
s.Line(point1=(40, 46),point2=(41, 45))
s.Line(point1=(41, 45),point2=(41, 44))
s.Line(point1=(41, 44),point2=(42, 43))
s.Line(point1=(42, 43),point2=(43, 42))
s.Line(point1=(43, 42),point2=(44, 42))
s.Line(point1=(44, 42),point2=(45, 42))
s.Line(point1=(45, 42),point2=(46, 42))
s.Line(point1=(46, 42),point2=(47, 42))
s.Line(point1=(47, 42),point2=(48, 41))
s.Line(point1=(48, 41),point2=(49, 41))
s.Line(point1=(49, 41),point2=(50, 41))
s.Line(point1=(50, 41),point2=(50, 40))
s.Line(point1=(50, 40),point2=(50, 39))
s.Line(point1=(50, 39),point2=(50, 38))
s.Line(point1=(50, 38),point2=(50, 37))
s.Line(point1=(50, 37),point2=(50, 36))
s.Line(point1=(50, 36),point2=(50, 35))
s.Line(point1=(50, 35),point2=(50, 34))
s.Line(point1=(50, 34),point2=(50, 33))
s.Line(point1=(50, 33),point2=(50, 32))
s.Line(point1=(50, 32),point2=(50, 31))
s.Line(point1=(50, 31),point2=(50, 30))
s.Line(point1=(50, 30),point2=(50, 29))
s.Line(point1=(50, 29),point2=(50, 28))
s.Line(point1=(50, 28),point2=(50, 27))
s.Line(point1=(50, 27),point2=(50, 26))
s.Line(point1=(50, 26),point2=(50, 25))
s.Line(point1=(50, 25),point2=(50, 24))
s.Line(point1=(50, 24),point2=(50, 23))
s.Line(point1=(50, 23),point2=(50, 22))
s.Line(point1=(50, 22),point2=(50, 21))
s.Line(point1=(50, 21),point2=(50, 20))
s.Line(point1=(50, 20),point2=(50, 19))
s.Line(point1=(50, 19),point2=(50, 18))
s.Line(point1=(50, 18),point2=(50, 17))
s.Line(point1=(50, 17),point2=(50, 16))
s.Line(point1=(50, 16),point2=(50, 15))
s.Line(point1=(50, 15),point2=(50, 14))
s.Line(point1=(50, 14),point2=(50, 13))
s.Line(point1=(50, 13),point2=(50, 12))
s.Line(point1=(50, 12),point2=(50, 11))
s.Line(point1=(50, 11),point2=(50, 10))
s.Line(point1=(50, 10),point2=(49, 10))
s.Line(point1=(49, 10),point2=(48, 10))
s.Line(point1=(48, 10),point2=(47, 9))
s.Line(point1=(47, 9),point2=(46, 9))
s.Line(point1=(46, 9),point2=(45, 9))
s.Line(point1=(45, 9),point2=(44, 9))
s.Line(point1=(44, 9),point2=(43, 9))
s.Line(point1=(43, 9),point2=(42, 8))
s.Line(point1=(42, 8),point2=(41, 7))
s.Line(point1=(41, 7),point2=(41, 6))
s.Line(point1=(41, 6),point2=(40, 5))
s.Line(point1=(40, 5),point2=(40, 4))
s.Line(point1=(40, 4),point2=(40, 3))
s.Line(point1=(40, 3),point2=(40, 2))
s.Line(point1=(40, 2),point2=(40, 1))
s.Line(point1=(40, 1),point2=(39, 1))
s.Line(point1=(39, 1),point2=(38, 1))
s.Line(point1=(38, 1),point2=(37, 1))
s.Line(point1=(37, 1),point2=(36, 1))
s.Line(point1=(36, 1),point2=(35, 1))
s.Line(point1=(35, 1),point2=(34, 1))
s.Line(point1=(34, 1),point2=(33, 1))
s.Line(point1=(33, 1),point2=(32, 1))
s.Line(point1=(32, 1),point2=(31, 1))
s.Line(point1=(31, 1),point2=(30, 1))
s.Line(point1=(30, 1),point2=(29, 1))
s.Line(point1=(29, 1),point2=(28, 1))
s.Line(point1=(28, 1),point2=(27, 1))
s.Line(point1=(27, 1),point2=(26, 1))
s.Line(point1=(26, 1),point2=(25, 1))
s.Line(point1=(25, 1),point2=(24, 1))
s.Line(point1=(24, 1),point2=(23, 1))
s.Line(point1=(23, 1),point2=(22, 1))
s.Line(point1=(22, 1),point2=(21, 1))
s.Line(point1=(21, 1),point2=(20, 1))
s.Line(point1=(20, 1),point2=(19, 1))
s.Line(point1=(19, 1),point2=(18, 1))
s.Line(point1=(18, 1),point2=(17, 1))
s.Line(point1=(17, 1),point2=(16, 1))
s.Line(point1=(16, 1),point2=(15, 1))
s.Line(point1=(15, 1),point2=(14, 1))
s.Line(point1=(14, 1),point2=(13, 1))
s.Line(point1=(13, 1),point2=(12, 1))
s.Line(point1=(12, 1),point2=(11, 1))
s.Line(point1=(18, 17),point2=(19, 16))
s.Line(point1=(19, 16),point2=(20, 16))
s.Line(point1=(20, 16),point2=(21, 16))
s.Line(point1=(21, 16),point2=(22, 16))
s.Line(point1=(22, 16),point2=(23, 16))
s.Line(point1=(23, 16),point2=(24, 16))
s.Line(point1=(24, 16),point2=(25, 17))
s.Line(point1=(25, 17),point2=(26, 17))
s.Line(point1=(26, 17),point2=(27, 16))
s.Line(point1=(27, 16),point2=(28, 16))
s.Line(point1=(28, 16),point2=(29, 16))
s.Line(point1=(29, 16),point2=(30, 16))
s.Line(point1=(30, 16),point2=(31, 16))
s.Line(point1=(31, 16),point2=(32, 16))
s.Line(point1=(32, 16),point2=(33, 17))
s.Line(point1=(33, 17),point2=(34, 17))
s.Line(point1=(34, 17),point2=(35, 17))
s.Line(point1=(35, 17),point2=(36, 17))
s.Line(point1=(36, 17),point2=(37, 18))
s.Line(point1=(37, 18),point2=(38, 19))
s.Line(point1=(38, 19),point2=(39, 20))
s.Line(point1=(39, 20),point2=(39, 21))
s.Line(point1=(39, 21),point2=(39, 22))
s.Line(point1=(39, 22),point2=(39, 23))
s.Line(point1=(39, 23),point2=(39, 24))
s.Line(point1=(39, 24),point2=(39, 25))
s.Line(point1=(39, 25),point2=(39, 26))
s.Line(point1=(39, 26),point2=(39, 27))
s.Line(point1=(39, 27),point2=(39, 28))
s.Line(point1=(39, 28),point2=(39, 29))
s.Line(point1=(39, 29),point2=(39, 30))
s.Line(point1=(39, 30),point2=(39, 31))
s.Line(point1=(39, 31),point2=(38, 32))
s.Line(point1=(38, 32),point2=(37, 33))
s.Line(point1=(37, 33),point2=(36, 34))
s.Line(point1=(36, 34),point2=(35, 34))
s.Line(point1=(35, 34),point2=(34, 34))
s.Line(point1=(34, 34),point2=(33, 34))
s.Line(point1=(33, 34),point2=(32, 35))
s.Line(point1=(32, 35),point2=(31, 35))
s.Line(point1=(31, 35),point2=(30, 35))
s.Line(point1=(30, 35),point2=(29, 35))
s.Line(point1=(29, 35),point2=(28, 35))
s.Line(point1=(28, 35),point2=(27, 35))
s.Line(point1=(27, 35),point2=(26, 34))
s.Line(point1=(26, 34),point2=(25, 34))
s.Line(point1=(25, 34),point2=(24, 35))
s.Line(point1=(24, 35),point2=(23, 35))
s.Line(point1=(23, 35),point2=(22, 35))
s.Line(point1=(22, 35),point2=(21, 35))
s.Line(point1=(21, 35),point2=(20, 35))
s.Line(point1=(20, 35),point2=(19, 35))
s.Line(point1=(19, 35),point2=(18, 34))
s.Line(point1=(18, 34),point2=(17, 34))
s.Line(point1=(17, 34),point2=(16, 34))
s.Line(point1=(16, 34),point2=(15, 34))
s.Line(point1=(15, 34),point2=(14, 33))
s.Line(point1=(14, 33),point2=(13, 32))
s.Line(point1=(13, 32),point2=(12, 31))
s.Line(point1=(12, 31),point2=(12, 30))
s.Line(point1=(12, 30),point2=(12, 29))
s.Line(point1=(12, 29),point2=(12, 28))
s.Line(point1=(12, 28),point2=(12, 27))
s.Line(point1=(12, 27),point2=(12, 26))
s.Line(point1=(12, 26),point2=(12, 25))
s.Line(point1=(12, 25),point2=(12, 24))
s.Line(point1=(12, 24),point2=(12, 23))
s.Line(point1=(12, 23),point2=(12, 22))
s.Line(point1=(12, 22),point2=(12, 21))
s.Line(point1=(12, 21),point2=(12, 20))
s.Line(point1=(12, 20),point2=(13, 19))
s.Line(point1=(13, 19),point2=(14, 18))
s.Line(point1=(14, 18),point2=(15, 17))
s.Line(point1=(15, 17),point2=(16, 17))
s.Line(point1=(16, 17),point2=(17, 17))
s.Line(point1=(17, 17),point2=(18, 17))
p = mdb.models["Model-1"].Part(name="S20_016", dimensionality=TWO_D_PLANAR,type=DEFORMABLE_BODY)
p = mdb.models["Model-1"].parts["S20_016"]
p.BaseShell(sketch=s)
s.unsetPrimaryObject()
p = mdb.models["Model-1"].parts["S20_016"]
session.viewports["Viewport: 1"].setValues(displayedObject=p)
del mdb.models["Model-1"].sketches["__profile__"]
session.viewports["Viewport: 1"].partDisplay.setValues(mesh=ON)
session.viewports["Viewport: 1"].partDisplay.meshOptions.setValues(meshTechnique=ON)
session.viewports["Viewport: 1"].partDisplay.geometryOptions.setValues(
referenceRepresentation=OFF)
p = mdb.models["Model-1"].parts["S20_016"]
p.seedPart(size=10, deviationFactor=0.1, minSizeFactor=0.1)
p = mdb.models["Model-1"].parts["S20_016"]
p.generateMesh()
s=p.edges
edges=s.findAt(((11, 1, 0),),((11, 2, 0),),((11, 3, 0),),((11, 4, 0),),((11, 5, 0),),((10, 6, 0),),((10, 7, 0),),((9, 8, 0),),((8, 9, 0),),((7, 9, 0),),((6, 9, 0),),((5, 9, 0),),((4, 9, 0),),((3, 10, 0),),((2, 10, 0),),((1, 10, 0),),((1, 11, 0),),((1, 12, 0),),((1, 13, 0),),((1, 14, 0),),((1, 15, 0),),((1, 16, 0),),((1, 17, 0),),((1, 18, 0),),((1, 19, 0),),((1, 20, 0),),((1, 21, 0),),((1, 22, 0),),((1, 23, 0),),((1, 24, 0),),((1, 25, 0),),((1, 26, 0),),((1, 27, 0),),((1, 28, 0),),((1, 29, 0),),((1, 30, 0),),((1, 31, 0),),((1, 32, 0),),((1, 33, 0),),((1, 34, 0),),((1, 35, 0),),((1, 36, 0),),((1, 37, 0),),((1, 38, 0),),((1, 39, 0),),((1, 40, 0),),((1, 41, 0),),((2, 41, 0),),((3, 41, 0),),((4, 42, 0),),((5, 42, 0),),((6, 42, 0),),((7, 42, 0),),((8, 42, 0),),((9, 43, 0),),((10, 44, 0),),((10, 45, 0),),((11, 46, 0),),((11, 47, 0),),((11, 48, 0),),((11, 49, 0),),((11, 50, 0),),)
p.Surface(side1Edges=edges, name="left")
edges=s.findAt(((39, 1, 0),),((38, 1, 0),),((37, 1, 0),),((36, 1, 0),),((35, 1, 0),),((34, 1, 0),),((33, 1, 0),),((32, 1, 0),),((31, 1, 0),),((30, 1, 0),),((29, 1, 0),),((28, 1, 0),),((27, 1, 0),),((26, 1, 0),),((25, 1, 0),),((24, 1, 0),),((23, 1, 0),),((22, 1, 0),),((21, 1, 0),),((20, 1, 0),),((19, 1, 0),),((18, 1, 0),),((17, 1, 0),),((16, 1, 0),),((15, 1, 0),),((14, 1, 0),),((13, 1, 0),),((12, 1, 0),),((11.5, 1, 0),),)
p.Surface(side1Edges=edges, name="bottom")
edges=s.findAt(((12, 50, 0),),((13, 50, 0),),((14, 50, 0),),((15, 50, 0),),((16, 50, 0),),((17, 50, 0),),((18, 50, 0),),((19, 50, 0),),((20, 50, 0),),((21, 50, 0),),((22, 50, 0),),((23, 50, 0),),((24, 50, 0),),((25, 50, 0),),((26, 50, 0),),((27, 50, 0),),((28, 50, 0),),((29, 50, 0),),((30, 50, 0),),((31, 50, 0),),((32, 50, 0),),((33, 50, 0),),((34, 50, 0),),((35, 50, 0),),((36, 50, 0),),((37, 50, 0),),((38, 50, 0),),((39, 50, 0),),((40, 50, 0),),)
p.Surface(side1Edges=edges, name="top")
edges=s.findAt(((40, 49, 0),),((40, 48, 0),),((40, 47, 0),),((40, 46, 0),),((41, 45, 0),),((41, 44, 0),),((42, 43, 0),),((43, 42, 0),),((44, 42, 0),),((45, 42, 0),),((46, 42, 0),),((47, 42, 0),),((48, 41, 0),),((49, 41, 0),),((50, 41, 0),),((50, 40, 0),),((50, 39, 0),),((50, 38, 0),),((50, 37, 0),),((50, 36, 0),),((50, 35, 0),),((50, 34, 0),),((50, 33, 0),),((50, 32, 0),),((50, 31, 0),),((50, 30, 0),),((50, 29, 0),),((50, 28, 0),),((50, 27, 0),),((50, 26, 0),),((50, 25, 0),),((50, 24, 0),),((50, 23, 0),),((50, 22, 0),),((50, 21, 0),),((50, 20, 0),),((50, 19, 0),),((50, 18, 0),),((50, 17, 0),),((50, 16, 0),),((50, 15, 0),),((50, 14, 0),),((50, 13, 0),),((50, 12, 0),),((50, 11, 0),),((50, 10, 0),),((49, 10, 0),),((48, 10, 0),),((47, 9, 0),),((46, 9, 0),),((45, 9, 0),),((44, 9, 0),),((43, 9, 0),),((42, 8, 0),),((41, 7, 0),),((41, 6, 0),),((40, 5, 0),),((40, 4, 0),),((40, 3, 0),),((40, 2, 0),),((40, 1, 0),),)
p.Surface(side1Edges=edges, name="right")
mdb.models["Model-1"].Material(name="Material-1")
mdb.models["Model-1"].materials["Material-1"].Elastic(table=((1E6, 0.3), ))
mdb.models["Model-1"].HomogeneousSolidSection(name="S20_016",
material="Material-1", thickness=None)
f = p.faces
faces= p.faces.findAt(((11,1,0), (40,50,0)), )
region = p.Set(faces=faces, name="S20_016")
p = mdb.models["Model-1"].parts["S20_016"]
p.SectionAssignment(region=region, sectionName="S20_016", offset=0.0,
offsetType=MIDDLE_SURFACE, offsetField="",
thicknessAssignment=FROM_SECTION)