# copyright - metaengineeringconsultants@gmail.com
# abaqus 2017 compatibility 
# bending of stud
# input data
from abaqus import *
from abaqusConstants import *
import __main__

def Macro5():
    import section
    import regionToolset
    import displayGroupMdbToolset as dgm
    import part
    import material
    import assembly
    import step
    import interaction
    import load
    import mesh
    import optimization
    import job
    import sketch
    import visualization
    import xyPlot
    import displayGroupOdbToolset as dgo
    import connectorBehavior
s = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=100.0)
g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints
s.setPrimaryObject(option=STANDALONE)
s.Line(point1=(12, 1),point2=(12, 2))
s.Line(point1=(12, 2),point2=(12, 3))
s.Line(point1=(12, 3),point2=(12, 4))
s.Line(point1=(12, 4),point2=(12, 5))
s.Line(point1=(12, 5),point2=(13, 5))
s.Line(point1=(13, 5),point2=(14, 6))
s.Line(point1=(14, 6),point2=(14, 7))
s.Line(point1=(14, 7),point2=(14, 8))
s.Line(point1=(14, 8),point2=(14, 9))
s.Line(point1=(14, 9),point2=(14, 10))
s.Line(point1=(14, 10),point2=(14, 11))
s.Line(point1=(14, 11),point2=(14, 12))
s.Line(point1=(14, 12),point2=(14, 13))
s.Line(point1=(14, 13),point2=(14, 14))
s.Line(point1=(14, 14),point2=(13, 15))
s.Line(point1=(13, 15),point2=(12, 15))
s.Line(point1=(12, 15),point2=(11, 15))
s.Line(point1=(11, 15),point2=(10, 15))
s.Line(point1=(10, 15),point2=(9, 15))
s.Line(point1=(9, 15),point2=(8, 15))
s.Line(point1=(8, 15),point2=(7, 15))
s.Line(point1=(7, 15),point2=(6, 15))
s.Line(point1=(6, 15),point2=(5, 15))
s.Line(point1=(5, 15),point2=(4, 15))
s.Line(point1=(4, 15),point2=(3, 15))
s.Line(point1=(3, 15),point2=(2, 15))
s.Line(point1=(2, 15),point2=(1, 15))
s.Line(point1=(1, 15),point2=(1, 16))
s.Line(point1=(1, 16),point2=(1, 17))
s.Line(point1=(1, 17),point2=(1, 18))
s.Line(point1=(1, 18),point2=(1, 19))
s.Line(point1=(1, 19),point2=(1, 20))
s.Line(point1=(1, 20),point2=(1, 21))
s.Line(point1=(1, 21),point2=(1, 22))
s.Line(point1=(1, 22),point2=(1, 23))
s.Line(point1=(1, 23),point2=(1, 24))
s.Line(point1=(1, 24),point2=(1, 25))
s.Line(point1=(1, 25),point2=(1, 26))
s.Line(point1=(1, 26),point2=(1, 27))
s.Line(point1=(1, 27),point2=(1, 28))
s.Line(point1=(1, 28),point2=(1, 29))
s.Line(point1=(1, 29),point2=(1, 30))
s.Line(point1=(1, 30),point2=(1, 31))
s.Line(point1=(1, 31),point2=(1, 32))
s.Line(point1=(1, 32),point2=(1, 33))
s.Line(point1=(1, 33),point2=(1, 34))
s.Line(point1=(1, 34),point2=(1, 35))
s.Line(point1=(1, 35),point2=(1, 36))
s.Line(point1=(1, 36),point2=(2, 36))
s.Line(point1=(2, 36),point2=(3, 36))
s.Line(point1=(3, 36),point2=(4, 36))
s.Line(point1=(4, 36),point2=(5, 36))
s.Line(point1=(5, 36),point2=(6, 36))
s.Line(point1=(6, 36),point2=(7, 36))
s.Line(point1=(7, 36),point2=(8, 36))
s.Line(point1=(8, 36),point2=(9, 36))
s.Line(point1=(9, 36),point2=(10, 36))
s.Line(point1=(10, 36),point2=(11, 36))
s.Line(point1=(11, 36),point2=(12, 36))
s.Line(point1=(12, 36),point2=(13, 36))
s.Line(point1=(13, 36),point2=(14, 37))
s.Line(point1=(14, 37),point2=(14, 38))
s.Line(point1=(14, 38),point2=(14, 39))
s.Line(point1=(14, 39),point2=(14, 40))
s.Line(point1=(14, 40),point2=(14, 41))
s.Line(point1=(14, 41),point2=(14, 42))
s.Line(point1=(14, 42),point2=(14, 43))
s.Line(point1=(14, 43),point2=(14, 44))
s.Line(point1=(14, 44),point2=(14, 45))
s.Line(point1=(14, 45),point2=(13, 46))
s.Line(point1=(13, 46),point2=(12, 46))
s.Line(point1=(12, 46),point2=(12, 47))
s.Line(point1=(12, 47),point2=(12, 48))
s.Line(point1=(12, 48),point2=(12, 49))
s.Line(point1=(12, 49),point2=(12, 50))
s.Line(point1=(12, 50),point2=(13, 50))
s.Line(point1=(13, 50),point2=(14, 50))
s.Line(point1=(14, 50),point2=(15, 50))
s.Line(point1=(15, 50),point2=(16, 50))
s.Line(point1=(16, 50),point2=(17, 50))
s.Line(point1=(17, 50),point2=(18, 50))
s.Line(point1=(18, 50),point2=(19, 50))
s.Line(point1=(19, 50),point2=(20, 50))
s.Line(point1=(20, 50),point2=(21, 50))
s.Line(point1=(21, 50),point2=(22, 50))
s.Line(point1=(22, 50),point2=(23, 50))
s.Line(point1=(23, 50),point2=(24, 50))
s.Line(point1=(24, 50),point2=(25, 50))
s.Line(point1=(25, 50),point2=(26, 50))
s.Line(point1=(26, 50),point2=(27, 50))
s.Line(point1=(27, 50),point2=(28, 50))
s.Line(point1=(28, 50),point2=(29, 50))
s.Line(point1=(29, 50),point2=(30, 50))
s.Line(point1=(30, 50),point2=(31, 50))
s.Line(point1=(31, 50),point2=(32, 50))
s.Line(point1=(32, 50),point2=(33, 50))
s.Line(point1=(33, 50),point2=(34, 50))
s.Line(point1=(34, 50),point2=(35, 50))
s.Line(point1=(35, 50),point2=(36, 50))
s.Line(point1=(36, 50),point2=(37, 50))
s.Line(point1=(37, 50),point2=(38, 50))
s.Line(point1=(38, 50),point2=(39, 50))
s.Line(point1=(39, 50),point2=(39, 49))
s.Line(point1=(39, 49),point2=(39, 48))
s.Line(point1=(39, 48),point2=(39, 47))
s.Line(point1=(39, 47),point2=(39, 46))
s.Line(point1=(39, 46),point2=(38, 46))
s.Line(point1=(38, 46),point2=(37, 45))
s.Line(point1=(37, 45),point2=(37, 44))
s.Line(point1=(37, 44),point2=(37, 43))
s.Line(point1=(37, 43),point2=(37, 42))
s.Line(point1=(37, 42),point2=(37, 41))
s.Line(point1=(37, 41),point2=(37, 40))
s.Line(point1=(37, 40),point2=(37, 39))
s.Line(point1=(37, 39),point2=(37, 38))
s.Line(point1=(37, 38),point2=(37, 37))
s.Line(point1=(37, 37),point2=(38, 36))
s.Line(point1=(38, 36),point2=(39, 36))
s.Line(point1=(39, 36),point2=(40, 36))
s.Line(point1=(40, 36),point2=(41, 36))
s.Line(point1=(41, 36),point2=(42, 36))
s.Line(point1=(42, 36),point2=(43, 36))
s.Line(point1=(43, 36),point2=(44, 36))
s.Line(point1=(44, 36),point2=(45, 36))
s.Line(point1=(45, 36),point2=(46, 36))
s.Line(point1=(46, 36),point2=(47, 36))
s.Line(point1=(47, 36),point2=(48, 36))
s.Line(point1=(48, 36),point2=(49, 36))
s.Line(point1=(49, 36),point2=(50, 36))
s.Line(point1=(50, 36),point2=(50, 35))
s.Line(point1=(50, 35),point2=(50, 34))
s.Line(point1=(50, 34),point2=(50, 33))
s.Line(point1=(50, 33),point2=(50, 32))
s.Line(point1=(50, 32),point2=(50, 31))
s.Line(point1=(50, 31),point2=(50, 30))
s.Line(point1=(50, 30),point2=(50, 29))
s.Line(point1=(50, 29),point2=(50, 28))
s.Line(point1=(50, 28),point2=(50, 27))
s.Line(point1=(50, 27),point2=(50, 26))
s.Line(point1=(50, 26),point2=(50, 25))
s.Line(point1=(50, 25),point2=(50, 24))
s.Line(point1=(50, 24),point2=(50, 23))
s.Line(point1=(50, 23),point2=(50, 22))
s.Line(point1=(50, 22),point2=(50, 21))
s.Line(point1=(50, 21),point2=(50, 20))
s.Line(point1=(50, 20),point2=(50, 19))
s.Line(point1=(50, 19),point2=(50, 18))
s.Line(point1=(50, 18),point2=(50, 17))
s.Line(point1=(50, 17),point2=(50, 16))
s.Line(point1=(50, 16),point2=(50, 15))
s.Line(point1=(50, 15),point2=(49, 15))
s.Line(point1=(49, 15),point2=(48, 15))
s.Line(point1=(48, 15),point2=(47, 15))
s.Line(point1=(47, 15),point2=(46, 15))
s.Line(point1=(46, 15),point2=(45, 15))
s.Line(point1=(45, 15),point2=(44, 15))
s.Line(point1=(44, 15),point2=(43, 15))
s.Line(point1=(43, 15),point2=(42, 15))
s.Line(point1=(42, 15),point2=(41, 15))
s.Line(point1=(41, 15),point2=(40, 15))
s.Line(point1=(40, 15),point2=(39, 15))
s.Line(point1=(39, 15),point2=(38, 15))
s.Line(point1=(38, 15),point2=(37, 14))
s.Line(point1=(37, 14),point2=(37, 13))
s.Line(point1=(37, 13),point2=(37, 12))
s.Line(point1=(37, 12),point2=(37, 11))
s.Line(point1=(37, 11),point2=(37, 10))
s.Line(point1=(37, 10),point2=(37, 9))
s.Line(point1=(37, 9),point2=(37, 8))
s.Line(point1=(37, 8),point2=(37, 7))
s.Line(point1=(37, 7),point2=(37, 6))
s.Line(point1=(37, 6),point2=(38, 5))
s.Line(point1=(38, 5),point2=(39, 5))
s.Line(point1=(39, 5),point2=(39, 4))
s.Line(point1=(39, 4),point2=(39, 3))
s.Line(point1=(39, 3),point2=(39, 2))
s.Line(point1=(39, 2),point2=(39, 1))
s.Line(point1=(39, 1),point2=(38, 1))
s.Line(point1=(38, 1),point2=(37, 1))
s.Line(point1=(37, 1),point2=(36, 1))
s.Line(point1=(36, 1),point2=(35, 1))
s.Line(point1=(35, 1),point2=(34, 1))
s.Line(point1=(34, 1),point2=(33, 1))
s.Line(point1=(33, 1),point2=(32, 1))
s.Line(point1=(32, 1),point2=(31, 1))
s.Line(point1=(31, 1),point2=(30, 1))
s.Line(point1=(30, 1),point2=(29, 1))
s.Line(point1=(29, 1),point2=(28, 1))
s.Line(point1=(28, 1),point2=(27, 1))
s.Line(point1=(27, 1),point2=(26, 1))
s.Line(point1=(26, 1),point2=(25, 1))
s.Line(point1=(25, 1),point2=(24, 1))
s.Line(point1=(24, 1),point2=(23, 1))
s.Line(point1=(23, 1),point2=(22, 1))
s.Line(point1=(22, 1),point2=(21, 1))
s.Line(point1=(21, 1),point2=(20, 1))
s.Line(point1=(20, 1),point2=(19, 1))
s.Line(point1=(19, 1),point2=(18, 1))
s.Line(point1=(18, 1),point2=(17, 1))
s.Line(point1=(17, 1),point2=(16, 1))
s.Line(point1=(16, 1),point2=(15, 1))
s.Line(point1=(15, 1),point2=(14, 1))
s.Line(point1=(14, 1),point2=(13, 1))
s.Line(point1=(13, 1),point2=(12, 1))
p = mdb.models["Model-1"].Part(name="S20_010", dimensionality=TWO_D_PLANAR,type=DEFORMABLE_BODY)
p = mdb.models["Model-1"].parts["S20_010"]
p.BaseShell(sketch=s)
s.unsetPrimaryObject()
p = mdb.models["Model-1"].parts["S20_010"]
session.viewports["Viewport: 1"].setValues(displayedObject=p)
del mdb.models["Model-1"].sketches["__profile__"]
session.viewports["Viewport: 1"].partDisplay.setValues(mesh=ON)
session.viewports["Viewport: 1"].partDisplay.meshOptions.setValues(meshTechnique=ON)
session.viewports["Viewport: 1"].partDisplay.geometryOptions.setValues(
referenceRepresentation=OFF)
p = mdb.models["Model-1"].parts["S20_010"]
p.seedPart(size=10, deviationFactor=0.1, minSizeFactor=0.1)
p = mdb.models["Model-1"].parts["S20_010"]
p.generateMesh()
s=p.edges
edges=s.findAt(((12, 1, 0),),((12, 2, 0),),((12, 3, 0),),((12, 4, 0),),((12, 5, 0),),((13, 5, 0),),((14, 6, 0),),((14, 7, 0),),((14, 8, 0),),((14, 9, 0),),((14, 10, 0),),((14, 11, 0),),((14, 12, 0),),((14, 13, 0),),((14, 14, 0),),((13, 15, 0),),((12, 15, 0),),((11, 15, 0),),((10, 15, 0),),((9, 15, 0),),((8, 15, 0),),((7, 15, 0),),((6, 15, 0),),((5, 15, 0),),((4, 15, 0),),((3, 15, 0),),((2, 15, 0),),((1, 15, 0),),((1, 16, 0),),((1, 17, 0),),((1, 18, 0),),((1, 19, 0),),((1, 20, 0),),((1, 21, 0),),((1, 22, 0),),((1, 23, 0),),((1, 24, 0),),((1, 25, 0),),((1, 26, 0),),((1, 27, 0),),((1, 28, 0),),((1, 29, 0),),((1, 30, 0),),((1, 31, 0),),((1, 32, 0),),((1, 33, 0),),((1, 34, 0),),((1, 35, 0),),((1, 36, 0),),((2, 36, 0),),((3, 36, 0),),((4, 36, 0),),((5, 36, 0),),((6, 36, 0),),((7, 36, 0),),((8, 36, 0),),((9, 36, 0),),((10, 36, 0),),((11, 36, 0),),((12, 36, 0),),((13, 36, 0),),((14, 37, 0),),((14, 38, 0),),((14, 39, 0),),((14, 40, 0),),((14, 41, 0),),((14, 42, 0),),((14, 43, 0),),((14, 44, 0),),((14, 45, 0),),((13, 46, 0),),((12, 46, 0),),((12, 47, 0),),((12, 48, 0),),((12, 49, 0),),((12, 50, 0),),)
p.Surface(side1Edges=edges, name="left")
edges=s.findAt(((38, 1, 0),),((37, 1, 0),),((36, 1, 0),),((35, 1, 0),),((34, 1, 0),),((33, 1, 0),),((32, 1, 0),),((31, 1, 0),),((30, 1, 0),),((29, 1, 0),),((28, 1, 0),),((27, 1, 0),),((26, 1, 0),),((25, 1, 0),),((24, 1, 0),),((23, 1, 0),),((22, 1, 0),),((21, 1, 0),),((20, 1, 0),),((19, 1, 0),),((18, 1, 0),),((17, 1, 0),),((16, 1, 0),),((15, 1, 0),),((14, 1, 0),),((13, 1, 0),),((12.5, 1, 0),),)
p.Surface(side1Edges=edges, name="bottom")
edges=s.findAt(((13, 50, 0),),((14, 50, 0),),((15, 50, 0),),((16, 50, 0),),((17, 50, 0),),((18, 50, 0),),((19, 50, 0),),((20, 50, 0),),((21, 50, 0),),((22, 50, 0),),((23, 50, 0),),((24, 50, 0),),((25, 50, 0),),((26, 50, 0),),((27, 50, 0),),((28, 50, 0),),((29, 50, 0),),((30, 50, 0),),((31, 50, 0),),((32, 50, 0),),((33, 50, 0),),((34, 50, 0),),((35, 50, 0),),((36, 50, 0),),((37, 50, 0),),((38, 50, 0),),((39, 50, 0),),)
p.Surface(side1Edges=edges, name="top")
edges=s.findAt(((39, 49, 0),),((39, 48, 0),),((39, 47, 0),),((39, 46, 0),),((38, 46, 0),),((37, 45, 0),),((37, 44, 0),),((37, 43, 0),),((37, 42, 0),),((37, 41, 0),),((37, 40, 0),),((37, 39, 0),),((37, 38, 0),),((37, 37, 0),),((38, 36, 0),),((39, 36, 0),),((40, 36, 0),),((41, 36, 0),),((42, 36, 0),),((43, 36, 0),),((44, 36, 0),),((45, 36, 0),),((46, 36, 0),),((47, 36, 0),),((48, 36, 0),),((49, 36, 0),),((50, 36, 0),),((50, 35, 0),),((50, 34, 0),),((50, 33, 0),),((50, 32, 0),),((50, 31, 0),),((50, 30, 0),),((50, 29, 0),),((50, 28, 0),),((50, 27, 0),),((50, 26, 0),),((50, 25, 0),),((50, 24, 0),),((50, 23, 0),),((50, 22, 0),),((50, 21, 0),),((50, 20, 0),),((50, 19, 0),),((50, 18, 0),),((50, 17, 0),),((50, 16, 0),),((50, 15, 0),),((49, 15, 0),),((48, 15, 0),),((47, 15, 0),),((46, 15, 0),),((45, 15, 0),),((44, 15, 0),),((43, 15, 0),),((42, 15, 0),),((41, 15, 0),),((40, 15, 0),),((39, 15, 0),),((38, 15, 0),),((37, 14, 0),),((37, 13, 0),),((37, 12, 0),),((37, 11, 0),),((37, 10, 0),),((37, 9, 0),),((37, 8, 0),),((37, 7, 0),),((37, 6, 0),),((38, 5, 0),),((39, 5, 0),),((39, 4, 0),),((39, 3, 0),),((39, 2, 0),),((39, 1, 0),),)
p.Surface(side1Edges=edges, name="right")
mdb.models["Model-1"].Material(name="Material-1")
mdb.models["Model-1"].materials["Material-1"].Elastic(table=((1E6, 0.3), ))
mdb.models["Model-1"].HomogeneousSolidSection(name="S20_010",
material="Material-1", thickness=None)
f = p.faces
faces= p.faces.findAt(((12,1,0), (39,50,0)), )
region = p.Set(faces=faces, name="S20_010")
p = mdb.models["Model-1"].parts["S20_010"]
p.SectionAssignment(region=region, sectionName="S20_010", offset=0.0,
offsetType=MIDDLE_SURFACE, offsetField="",
thicknessAssignment=FROM_SECTION)