# copyright - metaengineeringconsultants@gmail.com
# abaqus 2017 compatibility 
# bending of stud
# input data
from abaqus import *
from abaqusConstants import *
import __main__

def Macro5():
    import section
    import regionToolset
    import displayGroupMdbToolset as dgm
    import part
    import material
    import assembly
    import step
    import interaction
    import load
    import mesh
    import optimization
    import job
    import sketch
    import visualization
    import xyPlot
    import displayGroupOdbToolset as dgo
    import connectorBehavior
s = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=100.0)
g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints
s.setPrimaryObject(option=STANDALONE)
s.Line(point1=(7, 1),point2=(7, 2))
s.Line(point1=(7, 2),point2=(7, 3))
s.Line(point1=(7, 3),point2=(7, 4))
s.Line(point1=(7, 4),point2=(7, 5))
s.Line(point1=(7, 5),point2=(7, 6))
s.Line(point1=(7, 6),point2=(7, 7))
s.Line(point1=(7, 7),point2=(6, 8))
s.Line(point1=(6, 8),point2=(5, 9))
s.Line(point1=(5, 9),point2=(4, 9))
s.Line(point1=(4, 9),point2=(3, 9))
s.Line(point1=(3, 9),point2=(2, 9))
s.Line(point1=(2, 9),point2=(1, 9))
s.Line(point1=(1, 9),point2=(1, 10))
s.Line(point1=(1, 10),point2=(1, 11))
s.Line(point1=(1, 11),point2=(1, 12))
s.Line(point1=(1, 12),point2=(1, 13))
s.Line(point1=(1, 13),point2=(1, 14))
s.Line(point1=(1, 14),point2=(1, 15))
s.Line(point1=(1, 15),point2=(1, 16))
s.Line(point1=(1, 16),point2=(1, 17))
s.Line(point1=(1, 17),point2=(1, 18))
s.Line(point1=(1, 18),point2=(1, 19))
s.Line(point1=(1, 19),point2=(2, 20))
s.Line(point1=(2, 20),point2=(3, 21))
s.Line(point1=(3, 21),point2=(3, 22))
s.Line(point1=(3, 22),point2=(4, 22))
s.Line(point1=(4, 22),point2=(5, 23))
s.Line(point1=(5, 23),point2=(5, 24))
s.Line(point1=(5, 24),point2=(5, 25))
s.Line(point1=(5, 25),point2=(5, 26))
s.Line(point1=(5, 26),point2=(5, 27))
s.Line(point1=(5, 27),point2=(5, 28))
s.Line(point1=(5, 28),point2=(4, 29))
s.Line(point1=(4, 29),point2=(3, 29))
s.Line(point1=(3, 29),point2=(3, 30))
s.Line(point1=(3, 30),point2=(2, 31))
s.Line(point1=(2, 31),point2=(1, 32))
s.Line(point1=(1, 32),point2=(1, 33))
s.Line(point1=(1, 33),point2=(1, 34))
s.Line(point1=(1, 34),point2=(1, 35))
s.Line(point1=(1, 35),point2=(1, 36))
s.Line(point1=(1, 36),point2=(1, 37))
s.Line(point1=(1, 37),point2=(1, 38))
s.Line(point1=(1, 38),point2=(1, 39))
s.Line(point1=(1, 39),point2=(1, 40))
s.Line(point1=(1, 40),point2=(1, 41))
s.Line(point1=(1, 41),point2=(1, 42))
s.Line(point1=(1, 42),point2=(2, 42))
s.Line(point1=(2, 42),point2=(3, 42))
s.Line(point1=(3, 42),point2=(4, 42))
s.Line(point1=(4, 42),point2=(5, 42))
s.Line(point1=(5, 42),point2=(6, 43))
s.Line(point1=(6, 43),point2=(7, 44))
s.Line(point1=(7, 44),point2=(7, 45))
s.Line(point1=(7, 45),point2=(7, 46))
s.Line(point1=(7, 46),point2=(7, 47))
s.Line(point1=(7, 47),point2=(7, 48))
s.Line(point1=(7, 48),point2=(7, 49))
s.Line(point1=(7, 49),point2=(7, 50))
s.Line(point1=(7, 50),point2=(8, 50))
s.Line(point1=(8, 50),point2=(9, 50))
s.Line(point1=(9, 50),point2=(10, 50))
s.Line(point1=(10, 50),point2=(11, 50))
s.Line(point1=(11, 50),point2=(12, 50))
s.Line(point1=(12, 50),point2=(13, 50))
s.Line(point1=(13, 50),point2=(14, 50))
s.Line(point1=(14, 50),point2=(15, 50))
s.Line(point1=(15, 50),point2=(16, 50))
s.Line(point1=(16, 50),point2=(17, 50))
s.Line(point1=(17, 50),point2=(18, 50))
s.Line(point1=(18, 50),point2=(19, 50))
s.Line(point1=(19, 50),point2=(20, 50))
s.Line(point1=(20, 50),point2=(21, 50))
s.Line(point1=(21, 50),point2=(22, 50))
s.Line(point1=(22, 50),point2=(23, 50))
s.Line(point1=(23, 50),point2=(24, 50))
s.Line(point1=(24, 50),point2=(25, 50))
s.Line(point1=(25, 50),point2=(26, 50))
s.Line(point1=(26, 50),point2=(27, 50))
s.Line(point1=(27, 50),point2=(28, 50))
s.Line(point1=(28, 50),point2=(29, 50))
s.Line(point1=(29, 50),point2=(30, 50))
s.Line(point1=(30, 50),point2=(31, 50))
s.Line(point1=(31, 50),point2=(32, 50))
s.Line(point1=(32, 50),point2=(33, 50))
s.Line(point1=(33, 50),point2=(34, 50))
s.Line(point1=(34, 50),point2=(35, 50))
s.Line(point1=(35, 50),point2=(36, 50))
s.Line(point1=(36, 50),point2=(37, 50))
s.Line(point1=(37, 50),point2=(38, 50))
s.Line(point1=(38, 50),point2=(39, 50))
s.Line(point1=(39, 50),point2=(40, 50))
s.Line(point1=(40, 50),point2=(41, 50))
s.Line(point1=(41, 50),point2=(42, 50))
s.Line(point1=(42, 50),point2=(43, 50))
s.Line(point1=(43, 50),point2=(44, 50))
s.Line(point1=(44, 50),point2=(44, 49))
s.Line(point1=(44, 49),point2=(44, 48))
s.Line(point1=(44, 48),point2=(44, 47))
s.Line(point1=(44, 47),point2=(44, 46))
s.Line(point1=(44, 46),point2=(44, 45))
s.Line(point1=(44, 45),point2=(44, 44))
s.Line(point1=(44, 44),point2=(45, 43))
s.Line(point1=(45, 43),point2=(46, 42))
s.Line(point1=(46, 42),point2=(47, 42))
s.Line(point1=(47, 42),point2=(48, 42))
s.Line(point1=(48, 42),point2=(49, 42))
s.Line(point1=(49, 42),point2=(50, 42))
s.Line(point1=(50, 42),point2=(50, 41))
s.Line(point1=(50, 41),point2=(50, 40))
s.Line(point1=(50, 40),point2=(50, 39))
s.Line(point1=(50, 39),point2=(50, 38))
s.Line(point1=(50, 38),point2=(50, 37))
s.Line(point1=(50, 37),point2=(50, 36))
s.Line(point1=(50, 36),point2=(50, 35))
s.Line(point1=(50, 35),point2=(50, 34))
s.Line(point1=(50, 34),point2=(50, 33))
s.Line(point1=(50, 33),point2=(50, 32))
s.Line(point1=(50, 32),point2=(49, 31))
s.Line(point1=(49, 31),point2=(48, 30))
s.Line(point1=(48, 30),point2=(48, 29))
s.Line(point1=(48, 29),point2=(47, 29))
s.Line(point1=(47, 29),point2=(46, 28))
s.Line(point1=(46, 28),point2=(46, 27))
s.Line(point1=(46, 27),point2=(46, 26))
s.Line(point1=(46, 26),point2=(46, 25))
s.Line(point1=(46, 25),point2=(46, 24))
s.Line(point1=(46, 24),point2=(46, 23))
s.Line(point1=(46, 23),point2=(47, 22))
s.Line(point1=(47, 22),point2=(48, 22))
s.Line(point1=(48, 22),point2=(48, 21))
s.Line(point1=(48, 21),point2=(49, 20))
s.Line(point1=(49, 20),point2=(50, 19))
s.Line(point1=(50, 19),point2=(50, 18))
s.Line(point1=(50, 18),point2=(50, 17))
s.Line(point1=(50, 17),point2=(50, 16))
s.Line(point1=(50, 16),point2=(50, 15))
s.Line(point1=(50, 15),point2=(50, 14))
s.Line(point1=(50, 14),point2=(50, 13))
s.Line(point1=(50, 13),point2=(50, 12))
s.Line(point1=(50, 12),point2=(50, 11))
s.Line(point1=(50, 11),point2=(50, 10))
s.Line(point1=(50, 10),point2=(50, 9))
s.Line(point1=(50, 9),point2=(49, 9))
s.Line(point1=(49, 9),point2=(48, 9))
s.Line(point1=(48, 9),point2=(47, 9))
s.Line(point1=(47, 9),point2=(46, 9))
s.Line(point1=(46, 9),point2=(45, 8))
s.Line(point1=(45, 8),point2=(44, 7))
s.Line(point1=(44, 7),point2=(44, 6))
s.Line(point1=(44, 6),point2=(44, 5))
s.Line(point1=(44, 5),point2=(44, 4))
s.Line(point1=(44, 4),point2=(44, 3))
s.Line(point1=(44, 3),point2=(44, 2))
s.Line(point1=(44, 2),point2=(44, 1))
s.Line(point1=(44, 1),point2=(43, 1))
s.Line(point1=(43, 1),point2=(42, 1))
s.Line(point1=(42, 1),point2=(41, 1))
s.Line(point1=(41, 1),point2=(40, 1))
s.Line(point1=(40, 1),point2=(39, 1))
s.Line(point1=(39, 1),point2=(38, 1))
s.Line(point1=(38, 1),point2=(37, 1))
s.Line(point1=(37, 1),point2=(36, 1))
s.Line(point1=(36, 1),point2=(35, 1))
s.Line(point1=(35, 1),point2=(34, 1))
s.Line(point1=(34, 1),point2=(33, 1))
s.Line(point1=(33, 1),point2=(32, 1))
s.Line(point1=(32, 1),point2=(31, 1))
s.Line(point1=(31, 1),point2=(30, 1))
s.Line(point1=(30, 1),point2=(29, 1))
s.Line(point1=(29, 1),point2=(28, 1))
s.Line(point1=(28, 1),point2=(27, 1))
s.Line(point1=(27, 1),point2=(26, 1))
s.Line(point1=(26, 1),point2=(25, 1))
s.Line(point1=(25, 1),point2=(24, 1))
s.Line(point1=(24, 1),point2=(23, 1))
s.Line(point1=(23, 1),point2=(22, 1))
s.Line(point1=(22, 1),point2=(21, 1))
s.Line(point1=(21, 1),point2=(20, 1))
s.Line(point1=(20, 1),point2=(19, 1))
s.Line(point1=(19, 1),point2=(18, 1))
s.Line(point1=(18, 1),point2=(17, 1))
s.Line(point1=(17, 1),point2=(16, 1))
s.Line(point1=(16, 1),point2=(15, 1))
s.Line(point1=(15, 1),point2=(14, 1))
s.Line(point1=(14, 1),point2=(13, 1))
s.Line(point1=(13, 1),point2=(12, 1))
s.Line(point1=(12, 1),point2=(11, 1))
s.Line(point1=(11, 1),point2=(10, 1))
s.Line(point1=(10, 1),point2=(9, 1))
s.Line(point1=(9, 1),point2=(8, 1))
s.Line(point1=(8, 1),point2=(7, 1))
p = mdb.models["Model-1"].Part(name="S20_001", dimensionality=TWO_D_PLANAR,type=DEFORMABLE_BODY)
p = mdb.models["Model-1"].parts["S20_001"]
p.BaseShell(sketch=s)
s.unsetPrimaryObject()
p = mdb.models["Model-1"].parts["S20_001"]
session.viewports["Viewport: 1"].setValues(displayedObject=p)
del mdb.models["Model-1"].sketches["__profile__"]
session.viewports["Viewport: 1"].partDisplay.setValues(mesh=ON)
session.viewports["Viewport: 1"].partDisplay.meshOptions.setValues(meshTechnique=ON)
session.viewports["Viewport: 1"].partDisplay.geometryOptions.setValues(
referenceRepresentation=OFF)
p = mdb.models["Model-1"].parts["S20_001"]
p.seedPart(size=10, deviationFactor=0.1, minSizeFactor=0.1)
p = mdb.models["Model-1"].parts["S20_001"]
p.generateMesh()
s=p.edges
edges=s.findAt(((7, 1, 0),),((7, 2, 0),),((7, 3, 0),),((7, 4, 0),),((7, 5, 0),),((7, 6, 0),),((7, 7, 0),),((6, 8, 0),),((5, 9, 0),),((4, 9, 0),),((3, 9, 0),),((2, 9, 0),),((1, 9, 0),),((1, 10, 0),),((1, 11, 0),),((1, 12, 0),),((1, 13, 0),),((1, 14, 0),),((1, 15, 0),),((1, 16, 0),),((1, 17, 0),),((1, 18, 0),),((1, 19, 0),),((2, 20, 0),),((3, 21, 0),),((3, 22, 0),),((4, 22, 0),),((5, 23, 0),),((5, 24, 0),),((5, 25, 0),),((5, 26, 0),),((5, 27, 0),),((5, 28, 0),),((4, 29, 0),),((3, 29, 0),),((3, 30, 0),),((2, 31, 0),),((1, 32, 0),),((1, 33, 0),),((1, 34, 0),),((1, 35, 0),),((1, 36, 0),),((1, 37, 0),),((1, 38, 0),),((1, 39, 0),),((1, 40, 0),),((1, 41, 0),),((1, 42, 0),),((2, 42, 0),),((3, 42, 0),),((4, 42, 0),),((5, 42, 0),),((6, 43, 0),),((7, 44, 0),),((7, 45, 0),),((7, 46, 0),),((7, 47, 0),),((7, 48, 0),),((7, 49, 0),),((7, 50, 0),),)
p.Surface(side1Edges=edges, name="left")
edges=s.getByBoundingBox(7, 1, 0, 44, 1, 0,)
p.Surface(side1Edges=edges, name="bottom")
edges=s.findAt(((8, 50, 0),),((9, 50, 0),),((10, 50, 0),),((11, 50, 0),),((12, 50, 0),),((13, 50, 0),),((14, 50, 0),),((15, 50, 0),),((16, 50, 0),),((17, 50, 0),),((18, 50, 0),),((19, 50, 0),),((20, 50, 0),),((21, 50, 0),),((22, 50, 0),),((23, 50, 0),),((24, 50, 0),),((25, 50, 0),),((26, 50, 0),),((27, 50, 0),),((28, 50, 0),),((29, 50, 0),),((30, 50, 0),),((31, 50, 0),),((32, 50, 0),),((33, 50, 0),),((34, 50, 0),),((35, 50, 0),),((36, 50, 0),),((37, 50, 0),),((38, 50, 0),),((39, 50, 0),),((40, 50, 0),),((41, 50, 0),),((42, 50, 0),),((43, 50, 0),),((44, 50, 0),),)
p.Surface(side1Edges=edges, name="top")
edges=s.findAt(((44, 49, 0),),((44, 48, 0),),((44, 47, 0),),((44, 46, 0),),((44, 45, 0),),((44, 44, 0),),((45, 43, 0),),((46, 42, 0),),((47, 42, 0),),((48, 42, 0),),((49, 42, 0),),((50, 42, 0),),((50, 41, 0),),((50, 40, 0),),((50, 39, 0),),((50, 38, 0),),((50, 37, 0),),((50, 36, 0),),((50, 35, 0),),((50, 34, 0),),((50, 33, 0),),((50, 32, 0),),((49, 31, 0),),((48, 30, 0),),((48, 29, 0),),((47, 29, 0),),((46, 28, 0),),((46, 27, 0),),((46, 26, 0),),((46, 25, 0),),((46, 24, 0),),((46, 23, 0),),((47, 22, 0),),((48, 22, 0),),((48, 21, 0),),((49, 20, 0),),((50, 19, 0),),((50, 18, 0),),((50, 17, 0),),((50, 16, 0),),((50, 15, 0),),((50, 14, 0),),((50, 13, 0),),((50, 12, 0),),((50, 11, 0),),((50, 10, 0),),((50, 9, 0),),((49, 9, 0),),((48, 9, 0),),((47, 9, 0),),((46, 9, 0),),((45, 8, 0),),((44, 7, 0),),((44, 6, 0),),((44, 5, 0),),((44, 4, 0),),((44, 3, 0),),((44, 2, 0),),((44, 1, 0),),)
p.Surface(side1Edges=edges, name="right")
mdb.models["Model-1"].Material(name="Material-1")
mdb.models["Model-1"].materials["Material-1"].Elastic(table=((1E6, 0.3), ))
mdb.models["Model-1"].HomogeneousSolidSection(name="S20_001",
material="Material-1", thickness=None)
f = p.faces
faces= p.faces.findAt(((7,1,0), (44,50,0)), )
region = p.Set(faces=faces, name="S20_001")
p = mdb.models["Model-1"].parts["S20_001"]
p.SectionAssignment(region=region, sectionName="S20_001", offset=0.0,
offsetType=MIDDLE_SURFACE, offsetField="",
thicknessAssignment=FROM_SECTION)