# copyright - metaengineeringconsultants@gmail.com
# abaqus 2017 compatibility 
# bending of stud
# input data
from abaqus import *
from abaqusConstants import *
import __main__

def Macro5():
    import section
    import regionToolset
    import displayGroupMdbToolset as dgm
    import part
    import material
    import assembly
    import step
    import interaction
    import load
    import mesh
    import optimization
    import job
    import sketch
    import visualization
    import xyPlot
    import displayGroupOdbToolset as dgo
    import connectorBehavior
s = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=100.0)
g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints
s.setPrimaryObject(option=STANDALONE)
s.Line(point1=(1, 1),point2=(1, 2))
s.Line(point1=(1, 2),point2=(1, 3))
s.Line(point1=(1, 3),point2=(1, 4))
s.Line(point1=(1, 4),point2=(1, 5))
s.Line(point1=(1, 5),point2=(1, 6))
s.Line(point1=(1, 6),point2=(1, 7))
s.Line(point1=(1, 7),point2=(1, 8))
s.Line(point1=(1, 8),point2=(1, 9))
s.Line(point1=(1, 9),point2=(1, 10))
s.Line(point1=(1, 10),point2=(1, 11))
s.Line(point1=(1, 11),point2=(1, 12))
s.Line(point1=(1, 12),point2=(1, 13))
s.Line(point1=(1, 13),point2=(1, 14))
s.Line(point1=(1, 14),point2=(1, 15))
s.Line(point1=(1, 15),point2=(1, 16))
s.Line(point1=(1, 16),point2=(1, 17))
s.Line(point1=(1, 17),point2=(1, 18))
s.Line(point1=(1, 18),point2=(1, 19))
s.Line(point1=(1, 19),point2=(1, 20))
s.Line(point1=(1, 20),point2=(1, 21))
s.Line(point1=(1, 21),point2=(1, 22))
s.Line(point1=(1, 22),point2=(1, 23))
s.Line(point1=(1, 23),point2=(1, 24))
s.Line(point1=(1, 24),point2=(1, 25))
s.Line(point1=(1, 25),point2=(1, 26))
s.Line(point1=(1, 26),point2=(1, 27))
s.Line(point1=(1, 27),point2=(1, 28))
s.Line(point1=(1, 28),point2=(1, 29))
s.Line(point1=(1, 29),point2=(1, 30))
s.Line(point1=(1, 30),point2=(1, 31))
s.Line(point1=(1, 31),point2=(1, 32))
s.Line(point1=(1, 32),point2=(1, 33))
s.Line(point1=(1, 33),point2=(1, 34))
s.Line(point1=(1, 34),point2=(1, 35))
s.Line(point1=(1, 35),point2=(1, 36))
s.Line(point1=(1, 36),point2=(1, 37))
s.Line(point1=(1, 37),point2=(1, 38))
s.Line(point1=(1, 38),point2=(1, 39))
s.Line(point1=(1, 39),point2=(1, 40))
s.Line(point1=(1, 40),point2=(1, 41))
s.Line(point1=(1, 41),point2=(1, 42))
s.Line(point1=(1, 42),point2=(1, 43))
s.Line(point1=(1, 43),point2=(1, 44))
s.Line(point1=(1, 44),point2=(1, 45))
s.Line(point1=(1, 45),point2=(1, 46))
s.Line(point1=(1, 46),point2=(1, 47))
s.Line(point1=(1, 47),point2=(1, 48))
s.Line(point1=(1, 48),point2=(1, 49))
s.Line(point1=(1, 49),point2=(1, 50))
s.Line(point1=(1, 50),point2=(2, 50))
s.Line(point1=(2, 50),point2=(3, 50))
s.Line(point1=(3, 50),point2=(4, 50))
s.Line(point1=(4, 50),point2=(5, 50))
s.Line(point1=(5, 50),point2=(6, 50))
s.Line(point1=(6, 50),point2=(7, 50))
s.Line(point1=(7, 50),point2=(8, 50))
s.Line(point1=(8, 50),point2=(9, 50))
s.Line(point1=(9, 50),point2=(10, 50))
s.Line(point1=(10, 50),point2=(11, 50))
s.Line(point1=(11, 50),point2=(12, 50))
s.Line(point1=(12, 50),point2=(13, 50))
s.Line(point1=(13, 50),point2=(14, 50))
s.Line(point1=(14, 50),point2=(15, 50))
s.Line(point1=(15, 50),point2=(16, 50))
s.Line(point1=(16, 50),point2=(16, 49))
s.Line(point1=(16, 49),point2=(16, 48))
s.Line(point1=(16, 48),point2=(16, 47))
s.Line(point1=(16, 47),point2=(16, 46))
s.Line(point1=(16, 46),point2=(16, 45))
s.Line(point1=(16, 45),point2=(17, 44))
s.Line(point1=(17, 44),point2=(17, 43))
s.Line(point1=(17, 43),point2=(17, 42))
s.Line(point1=(17, 42),point2=(17, 41))
s.Line(point1=(17, 41),point2=(18, 40))
s.Line(point1=(18, 40),point2=(19, 39))
s.Line(point1=(19, 39),point2=(20, 38))
s.Line(point1=(20, 38),point2=(21, 38))
s.Line(point1=(21, 38),point2=(22, 38))
s.Line(point1=(22, 38),point2=(23, 37))
s.Line(point1=(23, 37),point2=(24, 37))
s.Line(point1=(24, 37),point2=(25, 37))
s.Line(point1=(25, 37),point2=(26, 37))
s.Line(point1=(26, 37),point2=(27, 37))
s.Line(point1=(27, 37),point2=(28, 37))
s.Line(point1=(28, 37),point2=(29, 38))
s.Line(point1=(29, 38),point2=(30, 38))
s.Line(point1=(30, 38),point2=(31, 38))
s.Line(point1=(31, 38),point2=(32, 39))
s.Line(point1=(32, 39),point2=(33, 40))
s.Line(point1=(33, 40),point2=(34, 41))
s.Line(point1=(34, 41),point2=(34, 42))
s.Line(point1=(34, 42),point2=(34, 43))
s.Line(point1=(34, 43),point2=(34, 44))
s.Line(point1=(34, 44),point2=(35, 45))
s.Line(point1=(35, 45),point2=(35, 46))
s.Line(point1=(35, 46),point2=(35, 47))
s.Line(point1=(35, 47),point2=(35, 48))
s.Line(point1=(35, 48),point2=(35, 49))
s.Line(point1=(35, 49),point2=(35, 50))
s.Line(point1=(35, 50),point2=(36, 50))
s.Line(point1=(36, 50),point2=(37, 50))
s.Line(point1=(37, 50),point2=(38, 50))
s.Line(point1=(38, 50),point2=(39, 50))
s.Line(point1=(39, 50),point2=(40, 50))
s.Line(point1=(40, 50),point2=(41, 50))
s.Line(point1=(41, 50),point2=(42, 50))
s.Line(point1=(42, 50),point2=(43, 50))
s.Line(point1=(43, 50),point2=(44, 50))
s.Line(point1=(44, 50),point2=(45, 50))
s.Line(point1=(45, 50),point2=(46, 50))
s.Line(point1=(46, 50),point2=(47, 50))
s.Line(point1=(47, 50),point2=(48, 50))
s.Line(point1=(48, 50),point2=(49, 50))
s.Line(point1=(49, 50),point2=(50, 50))
s.Line(point1=(50, 50),point2=(50, 49))
s.Line(point1=(50, 49),point2=(50, 48))
s.Line(point1=(50, 48),point2=(50, 47))
s.Line(point1=(50, 47),point2=(50, 46))
s.Line(point1=(50, 46),point2=(50, 45))
s.Line(point1=(50, 45),point2=(50, 44))
s.Line(point1=(50, 44),point2=(50, 43))
s.Line(point1=(50, 43),point2=(50, 42))
s.Line(point1=(50, 42),point2=(50, 41))
s.Line(point1=(50, 41),point2=(50, 40))
s.Line(point1=(50, 40),point2=(50, 39))
s.Line(point1=(50, 39),point2=(50, 38))
s.Line(point1=(50, 38),point2=(50, 37))
s.Line(point1=(50, 37),point2=(50, 36))
s.Line(point1=(50, 36),point2=(50, 35))
s.Line(point1=(50, 35),point2=(50, 34))
s.Line(point1=(50, 34),point2=(50, 33))
s.Line(point1=(50, 33),point2=(50, 32))
s.Line(point1=(50, 32),point2=(50, 31))
s.Line(point1=(50, 31),point2=(50, 30))
s.Line(point1=(50, 30),point2=(50, 29))
s.Line(point1=(50, 29),point2=(50, 28))
s.Line(point1=(50, 28),point2=(50, 27))
s.Line(point1=(50, 27),point2=(50, 26))
s.Line(point1=(50, 26),point2=(50, 25))
s.Line(point1=(50, 25),point2=(50, 24))
s.Line(point1=(50, 24),point2=(50, 23))
s.Line(point1=(50, 23),point2=(50, 22))
s.Line(point1=(50, 22),point2=(50, 21))
s.Line(point1=(50, 21),point2=(50, 20))
s.Line(point1=(50, 20),point2=(50, 19))
s.Line(point1=(50, 19),point2=(50, 18))
s.Line(point1=(50, 18),point2=(50, 17))
s.Line(point1=(50, 17),point2=(50, 16))
s.Line(point1=(50, 16),point2=(50, 15))
s.Line(point1=(50, 15),point2=(50, 14))
s.Line(point1=(50, 14),point2=(50, 13))
s.Line(point1=(50, 13),point2=(50, 12))
s.Line(point1=(50, 12),point2=(50, 11))
s.Line(point1=(50, 11),point2=(50, 10))
s.Line(point1=(50, 10),point2=(50, 9))
s.Line(point1=(50, 9),point2=(50, 8))
s.Line(point1=(50, 8),point2=(50, 7))
s.Line(point1=(50, 7),point2=(50, 6))
s.Line(point1=(50, 6),point2=(50, 5))
s.Line(point1=(50, 5),point2=(50, 4))
s.Line(point1=(50, 4),point2=(50, 3))
s.Line(point1=(50, 3),point2=(50, 2))
s.Line(point1=(50, 2),point2=(50, 1))
s.Line(point1=(50, 1),point2=(49, 1))
s.Line(point1=(49, 1),point2=(48, 1))
s.Line(point1=(48, 1),point2=(47, 1))
s.Line(point1=(47, 1),point2=(46, 1))
s.Line(point1=(46, 1),point2=(45, 1))
s.Line(point1=(45, 1),point2=(44, 1))
s.Line(point1=(44, 1),point2=(43, 1))
s.Line(point1=(43, 1),point2=(42, 1))
s.Line(point1=(42, 1),point2=(41, 1))
s.Line(point1=(41, 1),point2=(40, 1))
s.Line(point1=(40, 1),point2=(39, 1))
s.Line(point1=(39, 1),point2=(38, 1))
s.Line(point1=(38, 1),point2=(37, 1))
s.Line(point1=(37, 1),point2=(36, 1))
s.Line(point1=(36, 1),point2=(35, 1))
s.Line(point1=(35, 1),point2=(35, 2))
s.Line(point1=(35, 2),point2=(35, 3))
s.Line(point1=(35, 3),point2=(35, 4))
s.Line(point1=(35, 4),point2=(35, 5))
s.Line(point1=(35, 5),point2=(35, 6))
s.Line(point1=(35, 6),point2=(34, 7))
s.Line(point1=(34, 7),point2=(34, 8))
s.Line(point1=(34, 8),point2=(34, 9))
s.Line(point1=(34, 9),point2=(34, 10))
s.Line(point1=(34, 10),point2=(33, 11))
s.Line(point1=(33, 11),point2=(32, 12))
s.Line(point1=(32, 12),point2=(31, 13))
s.Line(point1=(31, 13),point2=(30, 13))
s.Line(point1=(30, 13),point2=(29, 13))
s.Line(point1=(29, 13),point2=(28, 14))
s.Line(point1=(28, 14),point2=(27, 14))
s.Line(point1=(27, 14),point2=(26, 14))
s.Line(point1=(26, 14),point2=(25, 14))
s.Line(point1=(25, 14),point2=(24, 14))
s.Line(point1=(24, 14),point2=(23, 14))
s.Line(point1=(23, 14),point2=(22, 13))
s.Line(point1=(22, 13),point2=(21, 13))
s.Line(point1=(21, 13),point2=(20, 13))
s.Line(point1=(20, 13),point2=(19, 12))
s.Line(point1=(19, 12),point2=(18, 11))
s.Line(point1=(18, 11),point2=(17, 10))
s.Line(point1=(17, 10),point2=(17, 9))
s.Line(point1=(17, 9),point2=(17, 8))
s.Line(point1=(17, 8),point2=(17, 7))
s.Line(point1=(17, 7),point2=(16, 6))
s.Line(point1=(16, 6),point2=(16, 5))
s.Line(point1=(16, 5),point2=(16, 4))
s.Line(point1=(16, 4),point2=(16, 3))
s.Line(point1=(16, 3),point2=(16, 2))
s.Line(point1=(16, 2),point2=(16, 1))
s.Line(point1=(16, 1),point2=(15, 1))
s.Line(point1=(15, 1),point2=(14, 1))
s.Line(point1=(14, 1),point2=(13, 1))
s.Line(point1=(13, 1),point2=(12, 1))
s.Line(point1=(12, 1),point2=(11, 1))
s.Line(point1=(11, 1),point2=(10, 1))
s.Line(point1=(10, 1),point2=(9, 1))
s.Line(point1=(9, 1),point2=(8, 1))
s.Line(point1=(8, 1),point2=(7, 1))
s.Line(point1=(7, 1),point2=(6, 1))
s.Line(point1=(6, 1),point2=(5, 1))
s.Line(point1=(5, 1),point2=(4, 1))
s.Line(point1=(4, 1),point2=(3, 1))
s.Line(point1=(3, 1),point2=(2, 1))
s.Line(point1=(2, 1),point2=(1, 1))
s.Line(point1=(22, 18),point2=(23, 17))
s.Line(point1=(23, 17),point2=(24, 17))
s.Line(point1=(24, 17),point2=(25, 17))
s.Line(point1=(25, 17),point2=(26, 17))
s.Line(point1=(26, 17),point2=(27, 17))
s.Line(point1=(27, 17),point2=(28, 17))
s.Line(point1=(28, 17),point2=(29, 18))
s.Line(point1=(29, 18),point2=(30, 18))
s.Line(point1=(30, 18),point2=(31, 18))
s.Line(point1=(31, 18),point2=(32, 19))
s.Line(point1=(32, 19),point2=(33, 20))
s.Line(point1=(33, 20),point2=(34, 21))
s.Line(point1=(34, 21),point2=(34, 22))
s.Line(point1=(34, 22),point2=(34, 23))
s.Line(point1=(34, 23),point2=(34, 24))
s.Line(point1=(34, 24),point2=(35, 25))
s.Line(point1=(35, 25),point2=(35, 26))
s.Line(point1=(35, 26),point2=(34, 27))
s.Line(point1=(34, 27),point2=(34, 28))
s.Line(point1=(34, 28),point2=(34, 29))
s.Line(point1=(34, 29),point2=(34, 30))
s.Line(point1=(34, 30),point2=(33, 31))
s.Line(point1=(33, 31),point2=(32, 32))
s.Line(point1=(32, 32),point2=(31, 33))
s.Line(point1=(31, 33),point2=(30, 33))
s.Line(point1=(30, 33),point2=(29, 33))
s.Line(point1=(29, 33),point2=(28, 34))
s.Line(point1=(28, 34),point2=(27, 34))
s.Line(point1=(27, 34),point2=(26, 34))
s.Line(point1=(26, 34),point2=(25, 34))
s.Line(point1=(25, 34),point2=(24, 34))
s.Line(point1=(24, 34),point2=(23, 34))
s.Line(point1=(23, 34),point2=(22, 33))
s.Line(point1=(22, 33),point2=(21, 33))
s.Line(point1=(21, 33),point2=(20, 33))
s.Line(point1=(20, 33),point2=(19, 32))
s.Line(point1=(19, 32),point2=(18, 31))
s.Line(point1=(18, 31),point2=(17, 30))
s.Line(point1=(17, 30),point2=(17, 29))
s.Line(point1=(17, 29),point2=(17, 28))
s.Line(point1=(17, 28),point2=(17, 27))
s.Line(point1=(17, 27),point2=(16, 26))
s.Line(point1=(16, 26),point2=(16, 25))
s.Line(point1=(16, 25),point2=(17, 24))
s.Line(point1=(17, 24),point2=(17, 23))
s.Line(point1=(17, 23),point2=(17, 22))
s.Line(point1=(17, 22),point2=(17, 21))
s.Line(point1=(17, 21),point2=(18, 20))
s.Line(point1=(18, 20),point2=(19, 19))
s.Line(point1=(19, 19),point2=(20, 18))
s.Line(point1=(20, 18),point2=(21, 18))
s.Line(point1=(21, 18),point2=(22, 18))
p = mdb.models["Model-1"].Part(name="S20_015", dimensionality=TWO_D_PLANAR,type=DEFORMABLE_BODY)
p = mdb.models["Model-1"].parts["S20_015"]
p.BaseShell(sketch=s)
s.unsetPrimaryObject()
p = mdb.models["Model-1"].parts["S20_015"]
session.viewports["Viewport: 1"].setValues(displayedObject=p)
del mdb.models["Model-1"].sketches["__profile__"]
session.viewports["Viewport: 1"].partDisplay.setValues(mesh=ON)
session.viewports["Viewport: 1"].partDisplay.meshOptions.setValues(meshTechnique=ON)
session.viewports["Viewport: 1"].partDisplay.geometryOptions.setValues(
referenceRepresentation=OFF)
p = mdb.models["Model-1"].parts["S20_015"]
p.seedPart(size=10, deviationFactor=0.1, minSizeFactor=0.1)
p = mdb.models["Model-1"].parts["S20_015"]
p.generateMesh()
s=p.edges
edges=s.findAt(((1, 1, 0),),((1, 2, 0),),((1, 3, 0),),((1, 4, 0),),((1, 5, 0),),((1, 6, 0),),((1, 7, 0),),((1, 8, 0),),((1, 9, 0),),((1, 10, 0),),((1, 11, 0),),((1, 12, 0),),((1, 13, 0),),((1, 14, 0),),((1, 15, 0),),((1, 16, 0),),((1, 17, 0),),((1, 18, 0),),((1, 19, 0),),((1, 20, 0),),((1, 21, 0),),((1, 22, 0),),((1, 23, 0),),((1, 24, 0),),((1, 25, 0),),((1, 26, 0),),((1, 27, 0),),((1, 28, 0),),((1, 29, 0),),((1, 30, 0),),((1, 31, 0),),((1, 32, 0),),((1, 33, 0),),((1, 34, 0),),((1, 35, 0),),((1, 36, 0),),((1, 37, 0),),((1, 38, 0),),((1, 39, 0),),((1, 40, 0),),((1, 41, 0),),((1, 42, 0),),((1, 43, 0),),((1, 44, 0),),((1, 45, 0),),((1, 46, 0),),((1, 47, 0),),((1, 48, 0),),((1, 49, 0),),((1, 50, 0),),)
p.Surface(side1Edges=edges, name="left")
edges=s.findAt(((49, 1, 0),),((48, 1, 0),),((47, 1, 0),),((46, 1, 0),),((45, 1, 0),),((44, 1, 0),),((43, 1, 0),),((42, 1, 0),),((41, 1, 0),),((40, 1, 0),),((39, 1, 0),),((38, 1, 0),),((37, 1, 0),),((36, 1, 0),),((35, 1, 0),),((35, 2, 0),),((35, 3, 0),),((35, 4, 0),),((35, 5, 0),),((35, 6, 0),),((34, 7, 0),),((34, 8, 0),),((34, 9, 0),),((34, 10, 0),),((33, 11, 0),),((32, 12, 0),),((31, 13, 0),),((30, 13, 0),),((29, 13, 0),),((28, 14, 0),),((27, 14, 0),),((26, 14, 0),),((25, 14, 0),),((24, 14, 0),),((23, 14, 0),),((22, 13, 0),),((21, 13, 0),),((20, 13, 0),),((19, 12, 0),),((18, 11, 0),),((17, 10, 0),),((17, 9, 0),),((17, 8, 0),),((17, 7, 0),),((16, 6, 0),),((16, 5, 0),),((16, 4, 0),),((16, 3, 0),),((16, 2, 0),),((16, 1, 0),),((15, 1, 0),),((14, 1, 0),),((13, 1, 0),),((12, 1, 0),),((11, 1, 0),),((10, 1, 0),),((9, 1, 0),),((8, 1, 0),),((7, 1, 0),),((6, 1, 0),),((5, 1, 0),),((4, 1, 0),),((3, 1, 0),),((2, 1, 0),),((1.5, 1, 0),),)
p.Surface(side1Edges=edges, name="bottom")
edges=s.findAt(((2, 50, 0),),((3, 50, 0),),((4, 50, 0),),((5, 50, 0),),((6, 50, 0),),((7, 50, 0),),((8, 50, 0),),((9, 50, 0),),((10, 50, 0),),((11, 50, 0),),((12, 50, 0),),((13, 50, 0),),((14, 50, 0),),((15, 50, 0),),((16, 50, 0),),((16, 49, 0),),((16, 48, 0),),((16, 47, 0),),((16, 46, 0),),((16, 45, 0),),((17, 44, 0),),((17, 43, 0),),((17, 42, 0),),((17, 41, 0),),((18, 40, 0),),((19, 39, 0),),((20, 38, 0),),((21, 38, 0),),((22, 38, 0),),((23, 37, 0),),((24, 37, 0),),((25, 37, 0),),((26, 37, 0),),((27, 37, 0),),((28, 37, 0),),((29, 38, 0),),((30, 38, 0),),((31, 38, 0),),((32, 39, 0),),((33, 40, 0),),((34, 41, 0),),((34, 42, 0),),((34, 43, 0),),((34, 44, 0),),((35, 45, 0),),((35, 46, 0),),((35, 47, 0),),((35, 48, 0),),((35, 49, 0),),((35, 50, 0),),((36, 50, 0),),((37, 50, 0),),((38, 50, 0),),((39, 50, 0),),((40, 50, 0),),((41, 50, 0),),((42, 50, 0),),((43, 50, 0),),((44, 50, 0),),((45, 50, 0),),((46, 50, 0),),((47, 50, 0),),((48, 50, 0),),((49, 50, 0),),((50, 50, 0),),)
p.Surface(side1Edges=edges, name="top")
edges=s.findAt(((50, 49, 0),),((50, 48, 0),),((50, 47, 0),),((50, 46, 0),),((50, 45, 0),),((50, 44, 0),),((50, 43, 0),),((50, 42, 0),),((50, 41, 0),),((50, 40, 0),),((50, 39, 0),),((50, 38, 0),),((50, 37, 0),),((50, 36, 0),),((50, 35, 0),),((50, 34, 0),),((50, 33, 0),),((50, 32, 0),),((50, 31, 0),),((50, 30, 0),),((50, 29, 0),),((50, 28, 0),),((50, 27, 0),),((50, 26, 0),),((50, 25, 0),),((50, 24, 0),),((50, 23, 0),),((50, 22, 0),),((50, 21, 0),),((50, 20, 0),),((50, 19, 0),),((50, 18, 0),),((50, 17, 0),),((50, 16, 0),),((50, 15, 0),),((50, 14, 0),),((50, 13, 0),),((50, 12, 0),),((50, 11, 0),),((50, 10, 0),),((50, 9, 0),),((50, 8, 0),),((50, 7, 0),),((50, 6, 0),),((50, 5, 0),),((50, 4, 0),),((50, 3, 0),),((50, 2, 0),),((50, 1, 0),),)
p.Surface(side1Edges=edges, name="right")
mdb.models["Model-1"].Material(name="Material-1")
mdb.models["Model-1"].materials["Material-1"].Elastic(table=((1E6, 0.3), ))
mdb.models["Model-1"].HomogeneousSolidSection(name="S20_015",
material="Material-1", thickness=None)
f = p.faces
faces= p.faces.findAt(((1,1,0), (50,50,0)), )
region = p.Set(faces=faces, name="S20_015")
p = mdb.models["Model-1"].parts["S20_015"]
p.SectionAssignment(region=region, sectionName="S20_015", offset=0.0,
offsetType=MIDDLE_SURFACE, offsetField="",
thicknessAssignment=FROM_SECTION)