from abaqus import *
from abaqusConstants import *
import __main__

def Macro5():
    import section
    import regionToolset
    import displayGroupMdbToolset as dgm
    import part
    import material
    import assembly
    import step
    import interaction
    import load
    import mesh
    import optimization
    import job
    import sketch
    import visualization
    import xyPlot
    import displayGroupOdbToolset as dgo
    import connectorBehavior
s = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=100.0)
g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints
s.setPrimaryObject(option=STANDALONE)
s.Line(point1=(1, 1),point2=(1, 2))
s.Line(point1=(1, 2),point2=(1, 3))
s.Line(point1=(1, 3),point2=(1, 4))
s.Line(point1=(1, 4),point2=(1, 5))
s.Line(point1=(1, 5),point2=(1, 6))
s.Line(point1=(1, 6),point2=(1, 7))
s.Line(point1=(1, 7),point2=(1, 8))
s.Line(point1=(1, 8),point2=(1, 9))
s.Line(point1=(1, 9),point2=(2, 9))
s.Line(point1=(2, 9),point2=(3, 9))
s.Line(point1=(3, 9),point2=(4, 9))
s.Line(point1=(4, 9),point2=(5, 9))
s.Line(point1=(5, 9),point2=(6, 9))
s.Line(point1=(6, 9),point2=(7, 9))
s.Line(point1=(7, 9),point2=(8, 10))
s.Line(point1=(8, 10),point2=(8, 11))
s.Line(point1=(8, 11),point2=(8, 12))
s.Line(point1=(8, 12),point2=(8, 13))
s.Line(point1=(8, 13),point2=(8, 14))
s.Line(point1=(8, 14),point2=(8, 15))
s.Line(point1=(8, 15),point2=(8, 16))
s.Line(point1=(8, 16),point2=(8, 17))
s.Line(point1=(8, 17),point2=(8, 18))
s.Line(point1=(8, 18),point2=(8, 19))
s.Line(point1=(8, 19),point2=(8, 20))
s.Line(point1=(8, 20),point2=(8, 21))
s.Line(point1=(8, 21),point2=(8, 22))
s.Line(point1=(8, 22),point2=(8, 23))
s.Line(point1=(8, 23),point2=(8, 24))
s.Line(point1=(8, 24),point2=(8, 25))
s.Line(point1=(8, 25),point2=(8, 26))
s.Line(point1=(8, 26),point2=(8, 27))
s.Line(point1=(8, 27),point2=(8, 28))
s.Line(point1=(8, 28),point2=(8, 29))
s.Line(point1=(8, 29),point2=(8, 30))
s.Line(point1=(8, 30),point2=(8, 31))
s.Line(point1=(8, 31),point2=(8, 32))
s.Line(point1=(8, 32),point2=(8, 33))
s.Line(point1=(8, 33),point2=(8, 34))
s.Line(point1=(8, 34),point2=(8, 35))
s.Line(point1=(8, 35),point2=(8, 36))
s.Line(point1=(8, 36),point2=(8, 37))
s.Line(point1=(8, 37),point2=(8, 38))
s.Line(point1=(8, 38),point2=(8, 39))
s.Line(point1=(8, 39),point2=(8, 40))
s.Line(point1=(8, 40),point2=(8, 41))
s.Line(point1=(8, 41),point2=(7, 42))
s.Line(point1=(7, 42),point2=(6, 42))
s.Line(point1=(6, 42),point2=(5, 42))
s.Line(point1=(5, 42),point2=(4, 42))
s.Line(point1=(4, 42),point2=(3, 42))
s.Line(point1=(3, 42),point2=(2, 42))
s.Line(point1=(2, 42),point2=(1, 42))
s.Line(point1=(1, 42),point2=(1, 43))
s.Line(point1=(1, 43),point2=(1, 44))
s.Line(point1=(1, 44),point2=(1, 45))
s.Line(point1=(1, 45),point2=(1, 46))
s.Line(point1=(1, 46),point2=(1, 47))
s.Line(point1=(1, 47),point2=(1, 48))
s.Line(point1=(1, 48),point2=(1, 49))
s.Line(point1=(1, 49),point2=(1, 50))
s.Line(point1=(1, 50),point2=(2, 50))
s.Line(point1=(2, 50),point2=(3, 50))
s.Line(point1=(3, 50),point2=(4, 50))
s.Line(point1=(4, 50),point2=(5, 50))
s.Line(point1=(5, 50),point2=(6, 50))
s.Line(point1=(6, 50),point2=(7, 50))
s.Line(point1=(7, 50),point2=(8, 50))
s.Line(point1=(8, 50),point2=(9, 50))
s.Line(point1=(9, 50),point2=(10, 50))
s.Line(point1=(10, 50),point2=(11, 50))
s.Line(point1=(11, 50),point2=(12, 50))
s.Line(point1=(12, 50),point2=(13, 50))
s.Line(point1=(13, 50),point2=(14, 50))
s.Line(point1=(14, 50),point2=(15, 50))
s.Line(point1=(15, 50),point2=(16, 50))
s.Line(point1=(16, 50),point2=(16, 49))
s.Line(point1=(16, 49),point2=(16, 48))
s.Line(point1=(16, 48),point2=(16, 47))
s.Line(point1=(16, 47),point2=(16, 46))
s.Line(point1=(16, 46),point2=(16, 45))
s.Line(point1=(16, 45),point2=(16, 44))
s.Line(point1=(16, 44),point2=(17, 43))
s.Line(point1=(17, 43),point2=(18, 42))
s.Line(point1=(18, 42),point2=(19, 42))
s.Line(point1=(19, 42),point2=(20, 42))
s.Line(point1=(20, 42),point2=(21, 42))
s.Line(point1=(21, 42),point2=(22, 42))
s.Line(point1=(22, 42),point2=(23, 42))
s.Line(point1=(23, 42),point2=(24, 42))
s.Line(point1=(24, 42),point2=(25, 42))
s.Line(point1=(25, 42),point2=(26, 42))
s.Line(point1=(26, 42),point2=(27, 42))
s.Line(point1=(27, 42),point2=(28, 42))
s.Line(point1=(28, 42),point2=(29, 42))
s.Line(point1=(29, 42),point2=(30, 42))
s.Line(point1=(30, 42),point2=(31, 42))
s.Line(point1=(31, 42),point2=(32, 42))
s.Line(point1=(32, 42),point2=(33, 42))
s.Line(point1=(33, 42),point2=(34, 43))
s.Line(point1=(34, 43),point2=(35, 44))
s.Line(point1=(35, 44),point2=(35, 45))
s.Line(point1=(35, 45),point2=(35, 46))
s.Line(point1=(35, 46),point2=(35, 47))
s.Line(point1=(35, 47),point2=(35, 48))
s.Line(point1=(35, 48),point2=(35, 49))
s.Line(point1=(35, 49),point2=(35, 50))
s.Line(point1=(35, 50),point2=(36, 50))
s.Line(point1=(36, 50),point2=(37, 50))
s.Line(point1=(37, 50),point2=(38, 50))
s.Line(point1=(38, 50),point2=(39, 50))
s.Line(point1=(39, 50),point2=(40, 50))
s.Line(point1=(40, 50),point2=(41, 50))
s.Line(point1=(41, 50),point2=(42, 50))
s.Line(point1=(42, 50),point2=(43, 50))
s.Line(point1=(43, 50),point2=(44, 50))
s.Line(point1=(44, 50),point2=(45, 50))
s.Line(point1=(45, 50),point2=(46, 50))
s.Line(point1=(46, 50),point2=(47, 50))
s.Line(point1=(47, 50),point2=(48, 50))
s.Line(point1=(48, 50),point2=(49, 50))
s.Line(point1=(49, 50),point2=(50, 50))
s.Line(point1=(50, 50),point2=(50, 49))
s.Line(point1=(50, 49),point2=(50, 48))
s.Line(point1=(50, 48),point2=(50, 47))
s.Line(point1=(50, 47),point2=(50, 46))
s.Line(point1=(50, 46),point2=(50, 45))
s.Line(point1=(50, 45),point2=(50, 44))
s.Line(point1=(50, 44),point2=(50, 43))
s.Line(point1=(50, 43),point2=(50, 42))
s.Line(point1=(50, 42),point2=(49, 42))
s.Line(point1=(49, 42),point2=(48, 42))
s.Line(point1=(48, 42),point2=(47, 42))
s.Line(point1=(47, 42),point2=(46, 42))
s.Line(point1=(46, 42),point2=(45, 42))
s.Line(point1=(45, 42),point2=(44, 42))
s.Line(point1=(44, 42),point2=(43, 41))
s.Line(point1=(43, 41),point2=(43, 40))
s.Line(point1=(43, 40),point2=(43, 39))
s.Line(point1=(43, 39),point2=(43, 38))
s.Line(point1=(43, 38),point2=(43, 37))
s.Line(point1=(43, 37),point2=(43, 36))
s.Line(point1=(43, 36),point2=(43, 35))
s.Line(point1=(43, 35),point2=(43, 34))
s.Line(point1=(43, 34),point2=(43, 33))
s.Line(point1=(43, 33),point2=(43, 32))
s.Line(point1=(43, 32),point2=(43, 31))
s.Line(point1=(43, 31),point2=(43, 30))
s.Line(point1=(43, 30),point2=(43, 29))
s.Line(point1=(43, 29),point2=(43, 28))
s.Line(point1=(43, 28),point2=(43, 27))
s.Line(point1=(43, 27),point2=(43, 26))
s.Line(point1=(43, 26),point2=(43, 25))
s.Line(point1=(43, 25),point2=(43, 24))
s.Line(point1=(43, 24),point2=(43, 23))
s.Line(point1=(43, 23),point2=(43, 22))
s.Line(point1=(43, 22),point2=(43, 21))
s.Line(point1=(43, 21),point2=(43, 20))
s.Line(point1=(43, 20),point2=(43, 19))
s.Line(point1=(43, 19),point2=(43, 18))
s.Line(point1=(43, 18),point2=(43, 17))
s.Line(point1=(43, 17),point2=(43, 16))
s.Line(point1=(43, 16),point2=(43, 15))
s.Line(point1=(43, 15),point2=(43, 14))
s.Line(point1=(43, 14),point2=(43, 13))
s.Line(point1=(43, 13),point2=(43, 12))
s.Line(point1=(43, 12),point2=(43, 11))
s.Line(point1=(43, 11),point2=(43, 10))
s.Line(point1=(43, 10),point2=(44, 9))
s.Line(point1=(44, 9),point2=(45, 9))
s.Line(point1=(45, 9),point2=(46, 9))
s.Line(point1=(46, 9),point2=(47, 9))
s.Line(point1=(47, 9),point2=(48, 9))
s.Line(point1=(48, 9),point2=(49, 9))
s.Line(point1=(49, 9),point2=(50, 9))
s.Line(point1=(50, 9),point2=(50, 8))
s.Line(point1=(50, 8),point2=(50, 7))
s.Line(point1=(50, 7),point2=(50, 6))
s.Line(point1=(50, 6),point2=(50, 5))
s.Line(point1=(50, 5),point2=(50, 4))
s.Line(point1=(50, 4),point2=(50, 3))
s.Line(point1=(50, 3),point2=(50, 2))
s.Line(point1=(50, 2),point2=(50, 1))
s.Line(point1=(50, 1),point2=(49, 1))
s.Line(point1=(49, 1),point2=(48, 1))
s.Line(point1=(48, 1),point2=(47, 1))
s.Line(point1=(47, 1),point2=(46, 1))
s.Line(point1=(46, 1),point2=(45, 1))
s.Line(point1=(45, 1),point2=(44, 1))
s.Line(point1=(44, 1),point2=(43, 1))
s.Line(point1=(43, 1),point2=(42, 1))
s.Line(point1=(42, 1),point2=(41, 1))
s.Line(point1=(41, 1),point2=(40, 1))
s.Line(point1=(40, 1),point2=(39, 1))
s.Line(point1=(39, 1),point2=(38, 1))
s.Line(point1=(38, 1),point2=(37, 1))
s.Line(point1=(37, 1),point2=(36, 1))
s.Line(point1=(36, 1),point2=(35, 1))
s.Line(point1=(35, 1),point2=(35, 2))
s.Line(point1=(35, 2),point2=(35, 3))
s.Line(point1=(35, 3),point2=(35, 4))
s.Line(point1=(35, 4),point2=(35, 5))
s.Line(point1=(35, 5),point2=(35, 6))
s.Line(point1=(35, 6),point2=(35, 7))
s.Line(point1=(35, 7),point2=(34, 8))
s.Line(point1=(34, 8),point2=(33, 9))
s.Line(point1=(33, 9),point2=(32, 9))
s.Line(point1=(32, 9),point2=(31, 9))
s.Line(point1=(31, 9),point2=(30, 9))
s.Line(point1=(30, 9),point2=(29, 9))
s.Line(point1=(29, 9),point2=(28, 9))
s.Line(point1=(28, 9),point2=(27, 9))
s.Line(point1=(27, 9),point2=(26, 9))
s.Line(point1=(26, 9),point2=(25, 9))
s.Line(point1=(25, 9),point2=(24, 9))
s.Line(point1=(24, 9),point2=(23, 9))
s.Line(point1=(23, 9),point2=(22, 9))
s.Line(point1=(22, 9),point2=(21, 9))
s.Line(point1=(21, 9),point2=(20, 9))
s.Line(point1=(20, 9),point2=(19, 9))
s.Line(point1=(19, 9),point2=(18, 9))
s.Line(point1=(18, 9),point2=(17, 8))
s.Line(point1=(17, 8),point2=(16, 7))
s.Line(point1=(16, 7),point2=(16, 6))
s.Line(point1=(16, 6),point2=(16, 5))
s.Line(point1=(16, 5),point2=(16, 4))
s.Line(point1=(16, 4),point2=(16, 3))
s.Line(point1=(16, 3),point2=(16, 2))
s.Line(point1=(16, 2),point2=(16, 1))
s.Line(point1=(16, 1),point2=(15, 1))
s.Line(point1=(15, 1),point2=(14, 1))
s.Line(point1=(14, 1),point2=(13, 1))
s.Line(point1=(13, 1),point2=(12, 1))
s.Line(point1=(12, 1),point2=(11, 1))
s.Line(point1=(11, 1),point2=(10, 1))
s.Line(point1=(10, 1),point2=(9, 1))
s.Line(point1=(9, 1),point2=(8, 1))
s.Line(point1=(8, 1),point2=(7, 1))
s.Line(point1=(7, 1),point2=(6, 1))
s.Line(point1=(6, 1),point2=(5, 1))
s.Line(point1=(5, 1),point2=(4, 1))
s.Line(point1=(4, 1),point2=(3, 1))
s.Line(point1=(3, 1),point2=(2, 1))
s.Line(point1=(2, 1),point2=(1, 1))
p = mdb.models["Model-1"].Part(name="S20_020", dimensionality=TWO_D_PLANAR,type=DEFORMABLE_BODY)
p = mdb.models["Model-1"].parts["S20_020"]
p.BaseShell(sketch=s)
s.unsetPrimaryObject()
p = mdb.models["Model-1"].parts["S20_020"]
session.viewports["Viewport: 1"].setValues(displayedObject=p)
del mdb.models["Model-1"].sketches["__profile__"]
session.viewports["Viewport: 1"].partDisplay.setValues(mesh=ON)
session.viewports["Viewport: 1"].partDisplay.meshOptions.setValues(meshTechnique=ON)
session.viewports["Viewport: 1"].partDisplay.geometryOptions.setValues(
referenceRepresentation=OFF)
p = mdb.models["Model-1"].parts["S20_020"]
p.seedPart(size=10, deviationFactor=0.1, minSizeFactor=0.1)
p = mdb.models["Model-1"].parts["S20_020"]
p.generateMesh()
s=p.edges
edges=s.findAt(((1, 1, 0),),((1, 2, 0),),((1, 3, 0),),((1, 4, 0),),((1, 5, 0),),((1, 6, 0),),((1, 7, 0),),((1, 8, 0),),((1, 9, 0),),((2, 9, 0),),((3, 9, 0),),((4, 9, 0),),((5, 9, 0),),((6, 9, 0),),((7, 9, 0),),((8, 10, 0),),((8, 11, 0),),((8, 12, 0),),((8, 13, 0),),((8, 14, 0),),((8, 15, 0),),((8, 16, 0),),((8, 17, 0),),((8, 18, 0),),((8, 19, 0),),((8, 20, 0),),((8, 21, 0),),((8, 22, 0),),((8, 23, 0),),((8, 24, 0),),((8, 25, 0),),((8, 26, 0),),((8, 27, 0),),((8, 28, 0),),((8, 29, 0),),((8, 30, 0),),((8, 31, 0),),((8, 32, 0),),((8, 33, 0),),((8, 34, 0),),((8, 35, 0),),((8, 36, 0),),((8, 37, 0),),((8, 38, 0),),((8, 39, 0),),((8, 40, 0),),((8, 41, 0),),((7, 42, 0),),((6, 42, 0),),((5, 42, 0),),((4, 42, 0),),((3, 42, 0),),((2, 42, 0),),((1, 42, 0),),((1, 43, 0),),((1, 44, 0),),((1, 45, 0),),((1, 46, 0),),((1, 47, 0),),((1, 48, 0),),((1, 49, 0),),((1, 50, 0),),)
p.Surface(side1Edges=edges, name="left")
edges=s.findAt(((49, 1, 0),),((48, 1, 0),),((47, 1, 0),),((46, 1, 0),),((45, 1, 0),),((44, 1, 0),),((43, 1, 0),),((42, 1, 0),),((41, 1, 0),),((40, 1, 0),),((39, 1, 0),),((38, 1, 0),),((37, 1, 0),),((36, 1, 0),),((35, 1, 0),),((35, 2, 0),),((35, 3, 0),),((35, 4, 0),),((35, 5, 0),),((35, 6, 0),),((35, 7, 0),),((34, 8, 0),),((33, 9, 0),),((32, 9, 0),),((31, 9, 0),),((30, 9, 0),),((29, 9, 0),),((28, 9, 0),),((27, 9, 0),),((26, 9, 0),),((25, 9, 0),),((24, 9, 0),),((23, 9, 0),),((22, 9, 0),),((21, 9, 0),),((20, 9, 0),),((19, 9, 0),),((18, 9, 0),),((17, 8, 0),),((16, 7, 0),),((16, 6, 0),),((16, 5, 0),),((16, 4, 0),),((16, 3, 0),),((16, 2, 0),),((16, 1, 0),),((15, 1, 0),),((14, 1, 0),),((13, 1, 0),),((12, 1, 0),),((11, 1, 0),),((10, 1, 0),),((9, 1, 0),),((8, 1, 0),),((7, 1, 0),),((6, 1, 0),),((5, 1, 0),),((4, 1, 0),),((3, 1, 0),),((2, 1, 0),),((1.5, 1, 0),),)
p.Surface(side1Edges=edges, name="bottom")
edges=s.findAt(((2, 50, 0),),((3, 50, 0),),((4, 50, 0),),((5, 50, 0),),((6, 50, 0),),((7, 50, 0),),((8, 50, 0),),((9, 50, 0),),((10, 50, 0),),((11, 50, 0),),((12, 50, 0),),((13, 50, 0),),((14, 50, 0),),((15, 50, 0),),((16, 50, 0),),((16, 49, 0),),((16, 48, 0),),((16, 47, 0),),((16, 46, 0),),((16, 45, 0),),((16, 44, 0),),((17, 43, 0),),((18, 42, 0),),((19, 42, 0),),((20, 42, 0),),((21, 42, 0),),((22, 42, 0),),((23, 42, 0),),((24, 42, 0),),((25, 42, 0),),((26, 42, 0),),((27, 42, 0),),((28, 42, 0),),((29, 42, 0),),((30, 42, 0),),((31, 42, 0),),((32, 42, 0),),((33, 42, 0),),((34, 43, 0),),((35, 44, 0),),((35, 45, 0),),((35, 46, 0),),((35, 47, 0),),((35, 48, 0),),((35, 49, 0),),((35, 50, 0),),((36, 50, 0),),((37, 50, 0),),((38, 50, 0),),((39, 50, 0),),((40, 50, 0),),((41, 50, 0),),((42, 50, 0),),((43, 50, 0),),((44, 50, 0),),((45, 50, 0),),((46, 50, 0),),((47, 50, 0),),((48, 50, 0),),((49, 50, 0),),((50, 50, 0),),)
p.Surface(side1Edges=edges, name="top")
edges=s.findAt(((50, 49, 0),),((50, 48, 0),),((50, 47, 0),),((50, 46, 0),),((50, 45, 0),),((50, 44, 0),),((50, 43, 0),),((50, 42, 0),),((49, 42, 0),),((48, 42, 0),),((47, 42, 0),),((46, 42, 0),),((45, 42, 0),),((44, 42, 0),),((43, 41, 0),),((43, 40, 0),),((43, 39, 0),),((43, 38, 0),),((43, 37, 0),),((43, 36, 0),),((43, 35, 0),),((43, 34, 0),),((43, 33, 0),),((43, 32, 0),),((43, 31, 0),),((43, 30, 0),),((43, 29, 0),),((43, 28, 0),),((43, 27, 0),),((43, 26, 0),),((43, 25, 0),),((43, 24, 0),),((43, 23, 0),),((43, 22, 0),),((43, 21, 0),),((43, 20, 0),),((43, 19, 0),),((43, 18, 0),),((43, 17, 0),),((43, 16, 0),),((43, 15, 0),),((43, 14, 0),),((43, 13, 0),),((43, 12, 0),),((43, 11, 0),),((43, 10, 0),),((44, 9, 0),),((45, 9, 0),),((46, 9, 0),),((47, 9, 0),),((48, 9, 0),),((49, 9, 0),),((50, 9, 0),),((50, 8, 0),),((50, 7, 0),),((50, 6, 0),),((50, 5, 0),),((50, 4, 0),),((50, 3, 0),),((50, 2, 0),),((50, 1, 0),),)
p.Surface(side1Edges=edges, name="right")
mdb.models["Model-1"].Material(name="Material-1")
mdb.models["Model-1"].materials["Material-1"].Elastic(table=((1E6, 0.3), ))
mdb.models["Model-1"].HomogeneousSolidSection(name="S20_020",
material="Material-1", thickness=None)
f = p.faces
faces= p.faces.findAt(((1,1,0), (50,50,0)), )
region = p.Set(faces=faces, name="S20_020")
p = mdb.models["Model-1"].parts["S20_020"]
p.SectionAssignment(region=region, sectionName="S20_020", offset=0.0,
offsetType=MIDDLE_SURFACE, offsetField="",
thicknessAssignment=FROM_SECTION)