# copyright - metaengineeringconsultants@gmail.com
# abaqus 2017 compatibility 
# bending of stud
# input data
from abaqus import *
from abaqusConstants import *
import __main__

def Macro5():
    import section
    import regionToolset
    import displayGroupMdbToolset as dgm
    import part
    import material
    import assembly
    import step
    import interaction
    import load
    import mesh
    import optimization
    import job
    import sketch
    import visualization
    import xyPlot
    import displayGroupOdbToolset as dgo
    import connectorBehavior
s = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=100.0)
g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints
s.setPrimaryObject(option=STANDALONE)
s.Line(point1=(4, 1),point2=(4, 2))
s.Line(point1=(4, 2),point2=(5, 2))
s.Line(point1=(5, 2),point2=(6, 2))
s.Line(point1=(6, 2),point2=(7, 2))
s.Line(point1=(7, 2),point2=(8, 2))
s.Line(point1=(8, 2),point2=(9, 2))
s.Line(point1=(9, 2),point2=(10, 2))
s.Line(point1=(10, 2),point2=(11, 3))
s.Line(point1=(11, 3),point2=(11, 4))
s.Line(point1=(11, 4),point2=(11, 5))
s.Line(point1=(11, 5),point2=(12, 6))
s.Line(point1=(12, 6),point2=(13, 7))
s.Line(point1=(13, 7),point2=(13, 8))
s.Line(point1=(13, 8),point2=(13, 9))
s.Line(point1=(13, 9),point2=(13, 10))
s.Line(point1=(13, 10),point2=(13, 11))
s.Line(point1=(13, 11),point2=(13, 12))
s.Line(point1=(13, 12),point2=(13, 13))
s.Line(point1=(13, 13),point2=(13, 14))
s.Line(point1=(13, 14),point2=(13, 15))
s.Line(point1=(13, 15),point2=(13, 16))
s.Line(point1=(13, 16),point2=(12, 17))
s.Line(point1=(12, 17),point2=(11, 18))
s.Line(point1=(11, 18),point2=(10, 18))
s.Line(point1=(10, 18),point2=(9, 18))
s.Line(point1=(9, 18),point2=(8, 18))
s.Line(point1=(8, 18),point2=(7, 18))
s.Line(point1=(7, 18),point2=(6, 18))
s.Line(point1=(6, 18),point2=(5, 18))
s.Line(point1=(5, 18),point2=(4, 18))
s.Line(point1=(4, 18),point2=(3, 18))
s.Line(point1=(3, 18),point2=(3, 19))
s.Line(point1=(3, 19),point2=(2, 20))
s.Line(point1=(2, 20),point2=(1, 21))
s.Line(point1=(1, 21),point2=(1, 22))
s.Line(point1=(1, 22),point2=(1, 23))
s.Line(point1=(1, 23),point2=(1, 24))
s.Line(point1=(1, 24),point2=(1, 25))
s.Line(point1=(1, 25),point2=(1, 26))
s.Line(point1=(1, 26),point2=(1, 27))
s.Line(point1=(1, 27),point2=(1, 28))
s.Line(point1=(1, 28),point2=(1, 29))
s.Line(point1=(1, 29),point2=(1, 30))
s.Line(point1=(1, 30),point2=(2, 31))
s.Line(point1=(2, 31),point2=(3, 32))
s.Line(point1=(3, 32),point2=(3, 33))
s.Line(point1=(3, 33),point2=(4, 33))
s.Line(point1=(4, 33),point2=(5, 33))
s.Line(point1=(5, 33),point2=(6, 33))
s.Line(point1=(6, 33),point2=(7, 33))
s.Line(point1=(7, 33),point2=(8, 33))
s.Line(point1=(8, 33),point2=(9, 33))
s.Line(point1=(9, 33),point2=(10, 33))
s.Line(point1=(10, 33),point2=(11, 33))
s.Line(point1=(11, 33),point2=(12, 34))
s.Line(point1=(12, 34),point2=(13, 35))
s.Line(point1=(13, 35),point2=(13, 36))
s.Line(point1=(13, 36),point2=(13, 37))
s.Line(point1=(13, 37),point2=(13, 38))
s.Line(point1=(13, 38),point2=(13, 39))
s.Line(point1=(13, 39),point2=(13, 40))
s.Line(point1=(13, 40),point2=(13, 41))
s.Line(point1=(13, 41),point2=(13, 42))
s.Line(point1=(13, 42),point2=(13, 43))
s.Line(point1=(13, 43),point2=(13, 44))
s.Line(point1=(13, 44),point2=(12, 45))
s.Line(point1=(12, 45),point2=(11, 46))
s.Line(point1=(11, 46),point2=(11, 47))
s.Line(point1=(11, 47),point2=(11, 48))
s.Line(point1=(11, 48),point2=(10, 49))
s.Line(point1=(10, 49),point2=(9, 49))
s.Line(point1=(9, 49),point2=(8, 49))
s.Line(point1=(8, 49),point2=(7, 49))
s.Line(point1=(7, 49),point2=(6, 49))
s.Line(point1=(6, 49),point2=(5, 49))
s.Line(point1=(5, 49),point2=(4, 49))
s.Line(point1=(4, 49),point2=(4, 50))
s.Line(point1=(4, 50),point2=(5, 50))
s.Line(point1=(5, 50),point2=(6, 50))
s.Line(point1=(6, 50),point2=(7, 50))
s.Line(point1=(7, 50),point2=(8, 50))
s.Line(point1=(8, 50),point2=(9, 50))
s.Line(point1=(9, 50),point2=(10, 50))
s.Line(point1=(10, 50),point2=(11, 50))
s.Line(point1=(11, 50),point2=(12, 50))
s.Line(point1=(12, 50),point2=(13, 50))
s.Line(point1=(13, 50),point2=(14, 50))
s.Line(point1=(14, 50),point2=(15, 50))
s.Line(point1=(15, 50),point2=(16, 50))
s.Line(point1=(16, 50),point2=(17, 50))
s.Line(point1=(17, 50),point2=(18, 50))
s.Line(point1=(18, 50),point2=(19, 50))
s.Line(point1=(19, 50),point2=(20, 50))
s.Line(point1=(20, 50),point2=(21, 50))
s.Line(point1=(21, 50),point2=(22, 50))
s.Line(point1=(22, 50),point2=(23, 50))
s.Line(point1=(23, 50),point2=(24, 50))
s.Line(point1=(24, 50),point2=(25, 50))
s.Line(point1=(25, 50),point2=(26, 50))
s.Line(point1=(26, 50),point2=(27, 50))
s.Line(point1=(27, 50),point2=(28, 50))
s.Line(point1=(28, 50),point2=(29, 50))
s.Line(point1=(29, 50),point2=(30, 50))
s.Line(point1=(30, 50),point2=(31, 50))
s.Line(point1=(31, 50),point2=(32, 50))
s.Line(point1=(32, 50),point2=(33, 50))
s.Line(point1=(33, 50),point2=(34, 50))
s.Line(point1=(34, 50),point2=(35, 50))
s.Line(point1=(35, 50),point2=(36, 50))
s.Line(point1=(36, 50),point2=(37, 50))
s.Line(point1=(37, 50),point2=(38, 50))
s.Line(point1=(38, 50),point2=(39, 50))
s.Line(point1=(39, 50),point2=(40, 50))
s.Line(point1=(40, 50),point2=(41, 50))
s.Line(point1=(41, 50),point2=(42, 50))
s.Line(point1=(42, 50),point2=(43, 50))
s.Line(point1=(43, 50),point2=(44, 50))
s.Line(point1=(44, 50),point2=(45, 50))
s.Line(point1=(45, 50),point2=(46, 50))
s.Line(point1=(46, 50),point2=(47, 50))
s.Line(point1=(47, 50),point2=(47, 49))
s.Line(point1=(47, 49),point2=(46, 49))
s.Line(point1=(46, 49),point2=(45, 49))
s.Line(point1=(45, 49),point2=(44, 49))
s.Line(point1=(44, 49),point2=(43, 49))
s.Line(point1=(43, 49),point2=(42, 49))
s.Line(point1=(42, 49),point2=(41, 49))
s.Line(point1=(41, 49),point2=(40, 48))
s.Line(point1=(40, 48),point2=(40, 47))
s.Line(point1=(40, 47),point2=(40, 46))
s.Line(point1=(40, 46),point2=(39, 45))
s.Line(point1=(39, 45),point2=(38, 44))
s.Line(point1=(38, 44),point2=(38, 43))
s.Line(point1=(38, 43),point2=(38, 42))
s.Line(point1=(38, 42),point2=(38, 41))
s.Line(point1=(38, 41),point2=(38, 40))
s.Line(point1=(38, 40),point2=(38, 39))
s.Line(point1=(38, 39),point2=(38, 38))
s.Line(point1=(38, 38),point2=(38, 37))
s.Line(point1=(38, 37),point2=(38, 36))
s.Line(point1=(38, 36),point2=(38, 35))
s.Line(point1=(38, 35),point2=(39, 34))
s.Line(point1=(39, 34),point2=(40, 33))
s.Line(point1=(40, 33),point2=(41, 33))
s.Line(point1=(41, 33),point2=(42, 33))
s.Line(point1=(42, 33),point2=(43, 33))
s.Line(point1=(43, 33),point2=(44, 33))
s.Line(point1=(44, 33),point2=(45, 33))
s.Line(point1=(45, 33),point2=(46, 33))
s.Line(point1=(46, 33),point2=(47, 33))
s.Line(point1=(47, 33),point2=(48, 33))
s.Line(point1=(48, 33),point2=(48, 32))
s.Line(point1=(48, 32),point2=(49, 31))
s.Line(point1=(49, 31),point2=(50, 30))
s.Line(point1=(50, 30),point2=(50, 29))
s.Line(point1=(50, 29),point2=(50, 28))
s.Line(point1=(50, 28),point2=(50, 27))
s.Line(point1=(50, 27),point2=(50, 26))
s.Line(point1=(50, 26),point2=(50, 25))
s.Line(point1=(50, 25),point2=(50, 24))
s.Line(point1=(50, 24),point2=(50, 23))
s.Line(point1=(50, 23),point2=(50, 22))
s.Line(point1=(50, 22),point2=(50, 21))
s.Line(point1=(50, 21),point2=(49, 20))
s.Line(point1=(49, 20),point2=(48, 19))
s.Line(point1=(48, 19),point2=(48, 18))
s.Line(point1=(48, 18),point2=(47, 18))
s.Line(point1=(47, 18),point2=(46, 18))
s.Line(point1=(46, 18),point2=(45, 18))
s.Line(point1=(45, 18),point2=(44, 18))
s.Line(point1=(44, 18),point2=(43, 18))
s.Line(point1=(43, 18),point2=(42, 18))
s.Line(point1=(42, 18),point2=(41, 18))
s.Line(point1=(41, 18),point2=(40, 18))
s.Line(point1=(40, 18),point2=(39, 17))
s.Line(point1=(39, 17),point2=(38, 16))
s.Line(point1=(38, 16),point2=(38, 15))
s.Line(point1=(38, 15),point2=(38, 14))
s.Line(point1=(38, 14),point2=(38, 13))
s.Line(point1=(38, 13),point2=(38, 12))
s.Line(point1=(38, 12),point2=(38, 11))
s.Line(point1=(38, 11),point2=(38, 10))
s.Line(point1=(38, 10),point2=(38, 9))
s.Line(point1=(38, 9),point2=(38, 8))
s.Line(point1=(38, 8),point2=(38, 7))
s.Line(point1=(38, 7),point2=(39, 6))
s.Line(point1=(39, 6),point2=(40, 5))
s.Line(point1=(40, 5),point2=(40, 4))
s.Line(point1=(40, 4),point2=(40, 3))
s.Line(point1=(40, 3),point2=(41, 2))
s.Line(point1=(41, 2),point2=(42, 2))
s.Line(point1=(42, 2),point2=(43, 2))
s.Line(point1=(43, 2),point2=(44, 2))
s.Line(point1=(44, 2),point2=(45, 2))
s.Line(point1=(45, 2),point2=(46, 2))
s.Line(point1=(46, 2),point2=(47, 2))
s.Line(point1=(47, 2),point2=(47, 1))
s.Line(point1=(47, 1),point2=(46, 1))
s.Line(point1=(46, 1),point2=(45, 1))
s.Line(point1=(45, 1),point2=(44, 1))
s.Line(point1=(44, 1),point2=(43, 1))
s.Line(point1=(43, 1),point2=(42, 1))
s.Line(point1=(42, 1),point2=(41, 1))
s.Line(point1=(41, 1),point2=(40, 1))
s.Line(point1=(40, 1),point2=(39, 1))
s.Line(point1=(39, 1),point2=(38, 1))
s.Line(point1=(38, 1),point2=(37, 1))
s.Line(point1=(37, 1),point2=(36, 1))
s.Line(point1=(36, 1),point2=(35, 1))
s.Line(point1=(35, 1),point2=(34, 1))
s.Line(point1=(34, 1),point2=(33, 1))
s.Line(point1=(33, 1),point2=(32, 1))
s.Line(point1=(32, 1),point2=(31, 1))
s.Line(point1=(31, 1),point2=(30, 1))
s.Line(point1=(30, 1),point2=(29, 1))
s.Line(point1=(29, 1),point2=(28, 1))
s.Line(point1=(28, 1),point2=(27, 1))
s.Line(point1=(27, 1),point2=(26, 1))
s.Line(point1=(26, 1),point2=(25, 1))
s.Line(point1=(25, 1),point2=(24, 1))
s.Line(point1=(24, 1),point2=(23, 1))
s.Line(point1=(23, 1),point2=(22, 1))
s.Line(point1=(22, 1),point2=(21, 1))
s.Line(point1=(21, 1),point2=(20, 1))
s.Line(point1=(20, 1),point2=(19, 1))
s.Line(point1=(19, 1),point2=(18, 1))
s.Line(point1=(18, 1),point2=(17, 1))
s.Line(point1=(17, 1),point2=(16, 1))
s.Line(point1=(16, 1),point2=(15, 1))
s.Line(point1=(15, 1),point2=(14, 1))
s.Line(point1=(14, 1),point2=(13, 1))
s.Line(point1=(13, 1),point2=(12, 1))
s.Line(point1=(12, 1),point2=(11, 1))
s.Line(point1=(11, 1),point2=(10, 1))
s.Line(point1=(10, 1),point2=(9, 1))
s.Line(point1=(9, 1),point2=(8, 1))
s.Line(point1=(8, 1),point2=(7, 1))
s.Line(point1=(7, 1),point2=(6, 1))
s.Line(point1=(6, 1),point2=(5, 1))
s.Line(point1=(5, 1),point2=(4, 1))
p = mdb.models["Model-1"].Part(name="S20_014", dimensionality=TWO_D_PLANAR,type=DEFORMABLE_BODY)
p = mdb.models["Model-1"].parts["S20_014"]
p.BaseShell(sketch=s)
s.unsetPrimaryObject()
p = mdb.models["Model-1"].parts["S20_014"]
session.viewports["Viewport: 1"].setValues(displayedObject=p)
del mdb.models["Model-1"].sketches["__profile__"]
session.viewports["Viewport: 1"].partDisplay.setValues(mesh=ON)
session.viewports["Viewport: 1"].partDisplay.meshOptions.setValues(meshTechnique=ON)
session.viewports["Viewport: 1"].partDisplay.geometryOptions.setValues(
referenceRepresentation=OFF)
p = mdb.models["Model-1"].parts["S20_014"]
p.seedPart(size=10, deviationFactor=0.1, minSizeFactor=0.1)
p = mdb.models["Model-1"].parts["S20_014"]
p.generateMesh()
s=p.edges
edges=s.findAt(((4, 1, 0),),((4, 2, 0),),((5, 2, 0),),((6, 2, 0),),((7, 2, 0),),((8, 2, 0),),((9, 2, 0),),((10, 2, 0),),((11, 3, 0),),((11, 4, 0),),((11, 5, 0),),((12, 6, 0),),((13, 7, 0),),((13, 8, 0),),((13, 9, 0),),((13, 10, 0),),((13, 11, 0),),((13, 12, 0),),((13, 13, 0),),((13, 14, 0),),((13, 15, 0),),((13, 16, 0),),((12, 17, 0),),((11, 18, 0),),((10, 18, 0),),((9, 18, 0),),((8, 18, 0),),((7, 18, 0),),((6, 18, 0),),((5, 18, 0),),((4, 18, 0),),((3, 18, 0),),((3, 19, 0),),((2, 20, 0),),((1, 21, 0),),((1, 22, 0),),((1, 23, 0),),((1, 24, 0),),((1, 25, 0),),((1, 26, 0),),((1, 27, 0),),((1, 28, 0),),((1, 29, 0),),((1, 30, 0),),((2, 31, 0),),((3, 32, 0),),((3, 33, 0),),((4, 33, 0),),((5, 33, 0),),((6, 33, 0),),((7, 33, 0),),((8, 33, 0),),((9, 33, 0),),((10, 33, 0),),((11, 33, 0),),((12, 34, 0),),((13, 35, 0),),((13, 36, 0),),((13, 37, 0),),((13, 38, 0),),((13, 39, 0),),((13, 40, 0),),((13, 41, 0),),((13, 42, 0),),((13, 43, 0),),((13, 44, 0),),((12, 45, 0),),((11, 46, 0),),((11, 47, 0),),((11, 48, 0),),((10, 49, 0),),((9, 49, 0),),((8, 49, 0),),((7, 49, 0),),((6, 49, 0),),((5, 49, 0),),((4, 49, 0),),((4, 50, 0),),)
p.Surface(side1Edges=edges, name="left")
edges=s.findAt(((46, 1, 0),),((45, 1, 0),),((44, 1, 0),),((43, 1, 0),),((42, 1, 0),),((41, 1, 0),),((40, 1, 0),),((39, 1, 0),),((38, 1, 0),),((37, 1, 0),),((36, 1, 0),),((35, 1, 0),),((34, 1, 0),),((33, 1, 0),),((32, 1, 0),),((31, 1, 0),),((30, 1, 0),),((29, 1, 0),),((28, 1, 0),),((27, 1, 0),),((26, 1, 0),),((25, 1, 0),),((24, 1, 0),),((23, 1, 0),),((22, 1, 0),),((21, 1, 0),),((20, 1, 0),),((19, 1, 0),),((18, 1, 0),),((17, 1, 0),),((16, 1, 0),),((15, 1, 0),),((14, 1, 0),),((13, 1, 0),),((12, 1, 0),),((11, 1, 0),),((10, 1, 0),),((9, 1, 0),),((8, 1, 0),),((7, 1, 0),),((6, 1, 0),),((5, 1, 0),),((4.5, 1, 0),),)
p.Surface(side1Edges=edges, name="bottom")
edges=s.findAt(((5, 50, 0),),((6, 50, 0),),((7, 50, 0),),((8, 50, 0),),((9, 50, 0),),((10, 50, 0),),((11, 50, 0),),((12, 50, 0),),((13, 50, 0),),((14, 50, 0),),((15, 50, 0),),((16, 50, 0),),((17, 50, 0),),((18, 50, 0),),((19, 50, 0),),((20, 50, 0),),((21, 50, 0),),((22, 50, 0),),((23, 50, 0),),((24, 50, 0),),((25, 50, 0),),((26, 50, 0),),((27, 50, 0),),((28, 50, 0),),((29, 50, 0),),((30, 50, 0),),((31, 50, 0),),((32, 50, 0),),((33, 50, 0),),((34, 50, 0),),((35, 50, 0),),((36, 50, 0),),((37, 50, 0),),((38, 50, 0),),((39, 50, 0),),((40, 50, 0),),((41, 50, 0),),((42, 50, 0),),((43, 50, 0),),((44, 50, 0),),((45, 50, 0),),((46, 50, 0),),((47, 50, 0),),)
p.Surface(side1Edges=edges, name="top")
edges=s.findAt(((47, 49, 0),),((46, 49, 0),),((45, 49, 0),),((44, 49, 0),),((43, 49, 0),),((42, 49, 0),),((41, 49, 0),),((40, 48, 0),),((40, 47, 0),),((40, 46, 0),),((39, 45, 0),),((38, 44, 0),),((38, 43, 0),),((38, 42, 0),),((38, 41, 0),),((38, 40, 0),),((38, 39, 0),),((38, 38, 0),),((38, 37, 0),),((38, 36, 0),),((38, 35, 0),),((39, 34, 0),),((40, 33, 0),),((41, 33, 0),),((42, 33, 0),),((43, 33, 0),),((44, 33, 0),),((45, 33, 0),),((46, 33, 0),),((47, 33, 0),),((48, 33, 0),),((48, 32, 0),),((49, 31, 0),),((50, 30, 0),),((50, 29, 0),),((50, 28, 0),),((50, 27, 0),),((50, 26, 0),),((50, 25, 0),),((50, 24, 0),),((50, 23, 0),),((50, 22, 0),),((50, 21, 0),),((49, 20, 0),),((48, 19, 0),),((48, 18, 0),),((47, 18, 0),),((46, 18, 0),),((45, 18, 0),),((44, 18, 0),),((43, 18, 0),),((42, 18, 0),),((41, 18, 0),),((40, 18, 0),),((39, 17, 0),),((38, 16, 0),),((38, 15, 0),),((38, 14, 0),),((38, 13, 0),),((38, 12, 0),),((38, 11, 0),),((38, 10, 0),),((38, 9, 0),),((38, 8, 0),),((38, 7, 0),),((39, 6, 0),),((40, 5, 0),),((40, 4, 0),),((40, 3, 0),),((41, 2, 0),),((42, 2, 0),),((43, 2, 0),),((44, 2, 0),),((45, 2, 0),),((46, 2, 0),),((47, 2, 0),),((47, 1, 0),),)
p.Surface(side1Edges=edges, name="right")
mdb.models["Model-1"].Material(name="Material-1")
mdb.models["Model-1"].materials["Material-1"].Elastic(table=((1E6, 0.3), ))
mdb.models["Model-1"].HomogeneousSolidSection(name="S20_014",
material="Material-1", thickness=None)
f = p.faces
faces= p.faces.findAt(((4,1,0), (47,50,0)), )
region = p.Set(faces=faces, name="S20_014")
p = mdb.models["Model-1"].parts["S20_014"]
p.SectionAssignment(region=region, sectionName="S20_014", offset=0.0,
offsetType=MIDDLE_SURFACE, offsetField="",
thicknessAssignment=FROM_SECTION)