# copyright - metaengineeringconsultants@gmail.com
# abaqus 2017 compatibility 
# bending of stud
# input data
from abaqus import *
from abaqusConstants import *
import __main__

def Macro5():
    import section
    import regionToolset
    import displayGroupMdbToolset as dgm
    import part
    import material
    import assembly
    import step
    import interaction
    import load
    import mesh
    import optimization
    import job
    import sketch
    import visualization
    import xyPlot
    import displayGroupOdbToolset as dgo
    import connectorBehavior
s = mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=100.0)
g, v, d, c = s.geometry, s.vertices, s.dimensions, s.constraints
s.setPrimaryObject(option=STANDALONE)
s.Line(point1=(1, 1),point2=(1, 2))
s.Line(point1=(1, 2),point2=(1, 3))
s.Line(point1=(1, 3),point2=(1, 4))
s.Line(point1=(1, 4),point2=(2, 5))
s.Line(point1=(2, 5),point2=(2, 6))
s.Line(point1=(2, 6),point2=(2, 7))
s.Line(point1=(2, 7),point2=(2, 8))
s.Line(point1=(2, 8),point2=(1, 9))
s.Line(point1=(1, 9),point2=(1, 10))
s.Line(point1=(1, 10),point2=(1, 11))
s.Line(point1=(1, 11),point2=(1, 12))
s.Line(point1=(1, 12),point2=(1, 13))
s.Line(point1=(1, 13),point2=(1, 14))
s.Line(point1=(1, 14),point2=(1, 15))
s.Line(point1=(1, 15),point2=(1, 16))
s.Line(point1=(1, 16),point2=(1, 17))
s.Line(point1=(1, 17),point2=(1, 18))
s.Line(point1=(1, 18),point2=(1, 19))
s.Line(point1=(1, 19),point2=(1, 20))
s.Line(point1=(1, 20),point2=(1, 21))
s.Line(point1=(1, 21),point2=(1, 22))
s.Line(point1=(1, 22),point2=(1, 23))
s.Line(point1=(1, 23),point2=(1, 24))
s.Line(point1=(1, 24),point2=(1, 25))
s.Line(point1=(1, 25),point2=(1, 26))
s.Line(point1=(1, 26),point2=(1, 27))
s.Line(point1=(1, 27),point2=(1, 28))
s.Line(point1=(1, 28),point2=(1, 29))
s.Line(point1=(1, 29),point2=(1, 30))
s.Line(point1=(1, 30),point2=(1, 31))
s.Line(point1=(1, 31),point2=(1, 32))
s.Line(point1=(1, 32),point2=(1, 33))
s.Line(point1=(1, 33),point2=(1, 34))
s.Line(point1=(1, 34),point2=(1, 35))
s.Line(point1=(1, 35),point2=(1, 36))
s.Line(point1=(1, 36),point2=(1, 37))
s.Line(point1=(1, 37),point2=(1, 38))
s.Line(point1=(1, 38),point2=(1, 39))
s.Line(point1=(1, 39),point2=(1, 40))
s.Line(point1=(1, 40),point2=(1, 41))
s.Line(point1=(1, 41),point2=(1, 42))
s.Line(point1=(1, 42),point2=(2, 43))
s.Line(point1=(2, 43),point2=(2, 44))
s.Line(point1=(2, 44),point2=(2, 45))
s.Line(point1=(2, 45),point2=(2, 46))
s.Line(point1=(2, 46),point2=(1, 47))
s.Line(point1=(1, 47),point2=(1, 48))
s.Line(point1=(1, 48),point2=(1, 49))
s.Line(point1=(1, 49),point2=(1, 50))
s.Line(point1=(1, 50),point2=(2, 50))
s.Line(point1=(2, 50),point2=(3, 50))
s.Line(point1=(3, 50),point2=(3, 49))
s.Line(point1=(3, 49),point2=(3, 48))
s.Line(point1=(3, 48),point2=(4, 47))
s.Line(point1=(4, 47),point2=(5, 47))
s.Line(point1=(5, 47),point2=(5, 46))
s.Line(point1=(5, 46),point2=(6, 45))
s.Line(point1=(6, 45),point2=(7, 45))
s.Line(point1=(7, 45),point2=(7, 44))
s.Line(point1=(7, 44),point2=(8, 43))
s.Line(point1=(8, 43),point2=(9, 42))
s.Line(point1=(9, 42),point2=(10, 42))
s.Line(point1=(10, 42),point2=(11, 42))
s.Line(point1=(11, 42),point2=(11, 41))
s.Line(point1=(11, 41),point2=(12, 40))
s.Line(point1=(12, 40),point2=(13, 40))
s.Line(point1=(13, 40),point2=(14, 40))
s.Line(point1=(14, 40),point2=(15, 40))
s.Line(point1=(15, 40),point2=(16, 40))
s.Line(point1=(16, 40),point2=(17, 40))
s.Line(point1=(17, 40),point2=(18, 40))
s.Line(point1=(18, 40),point2=(19, 40))
s.Line(point1=(19, 40),point2=(20, 41))
s.Line(point1=(20, 41),point2=(20, 42))
s.Line(point1=(20, 42),point2=(20, 43))
s.Line(point1=(20, 43),point2=(21, 42))
s.Line(point1=(21, 42),point2=(22, 42))
s.Line(point1=(22, 42),point2=(23, 43))
s.Line(point1=(23, 43),point2=(23, 44))
s.Line(point1=(23, 44),point2=(23, 45))
s.Line(point1=(23, 45),point2=(24, 45))
s.Line(point1=(24, 45),point2=(25, 45))
s.Line(point1=(25, 45),point2=(26, 45))
s.Line(point1=(26, 45),point2=(27, 45))
s.Line(point1=(27, 45),point2=(28, 45))
s.Line(point1=(28, 45),point2=(28, 44))
s.Line(point1=(28, 44),point2=(28, 43))
s.Line(point1=(28, 43),point2=(29, 42))
s.Line(point1=(29, 42),point2=(30, 42))
s.Line(point1=(30, 42),point2=(31, 43))
s.Line(point1=(31, 43),point2=(31, 42))
s.Line(point1=(31, 42),point2=(31, 41))
s.Line(point1=(31, 41),point2=(32, 40))
s.Line(point1=(32, 40),point2=(33, 40))
s.Line(point1=(33, 40),point2=(34, 40))
s.Line(point1=(34, 40),point2=(35, 40))
s.Line(point1=(35, 40),point2=(36, 40))
s.Line(point1=(36, 40),point2=(37, 40))
s.Line(point1=(37, 40),point2=(38, 40))
s.Line(point1=(38, 40),point2=(39, 40))
s.Line(point1=(39, 40),point2=(40, 41))
s.Line(point1=(40, 41),point2=(40, 42))
s.Line(point1=(40, 42),point2=(41, 42))
s.Line(point1=(41, 42),point2=(42, 42))
s.Line(point1=(42, 42),point2=(43, 43))
s.Line(point1=(43, 43),point2=(44, 44))
s.Line(point1=(44, 44),point2=(44, 45))
s.Line(point1=(44, 45),point2=(45, 45))
s.Line(point1=(45, 45),point2=(46, 46))
s.Line(point1=(46, 46),point2=(46, 47))
s.Line(point1=(46, 47),point2=(47, 47))
s.Line(point1=(47, 47),point2=(48, 48))
s.Line(point1=(48, 48),point2=(48, 49))
s.Line(point1=(48, 49),point2=(48, 50))
s.Line(point1=(48, 50),point2=(49, 50))
s.Line(point1=(49, 50),point2=(50, 50))
s.Line(point1=(50, 50),point2=(50, 49))
s.Line(point1=(50, 49),point2=(50, 48))
s.Line(point1=(50, 48),point2=(50, 47))
s.Line(point1=(50, 47),point2=(49, 46))
s.Line(point1=(49, 46),point2=(49, 45))
s.Line(point1=(49, 45),point2=(49, 44))
s.Line(point1=(49, 44),point2=(49, 43))
s.Line(point1=(49, 43),point2=(50, 42))
s.Line(point1=(50, 42),point2=(50, 41))
s.Line(point1=(50, 41),point2=(50, 40))
s.Line(point1=(50, 40),point2=(50, 39))
s.Line(point1=(50, 39),point2=(50, 38))
s.Line(point1=(50, 38),point2=(50, 37))
s.Line(point1=(50, 37),point2=(50, 36))
s.Line(point1=(50, 36),point2=(50, 35))
s.Line(point1=(50, 35),point2=(50, 34))
s.Line(point1=(50, 34),point2=(50, 33))
s.Line(point1=(50, 33),point2=(50, 32))
s.Line(point1=(50, 32),point2=(50, 31))
s.Line(point1=(50, 31),point2=(50, 30))
s.Line(point1=(50, 30),point2=(50, 29))
s.Line(point1=(50, 29),point2=(50, 28))
s.Line(point1=(50, 28),point2=(50, 27))
s.Line(point1=(50, 27),point2=(50, 26))
s.Line(point1=(50, 26),point2=(50, 25))
s.Line(point1=(50, 25),point2=(50, 24))
s.Line(point1=(50, 24),point2=(50, 23))
s.Line(point1=(50, 23),point2=(50, 22))
s.Line(point1=(50, 22),point2=(50, 21))
s.Line(point1=(50, 21),point2=(50, 20))
s.Line(point1=(50, 20),point2=(50, 19))
s.Line(point1=(50, 19),point2=(50, 18))
s.Line(point1=(50, 18),point2=(50, 17))
s.Line(point1=(50, 17),point2=(50, 16))
s.Line(point1=(50, 16),point2=(50, 15))
s.Line(point1=(50, 15),point2=(50, 14))
s.Line(point1=(50, 14),point2=(50, 13))
s.Line(point1=(50, 13),point2=(50, 12))
s.Line(point1=(50, 12),point2=(50, 11))
s.Line(point1=(50, 11),point2=(50, 10))
s.Line(point1=(50, 10),point2=(50, 9))
s.Line(point1=(50, 9),point2=(49, 8))
s.Line(point1=(49, 8),point2=(49, 7))
s.Line(point1=(49, 7),point2=(49, 6))
s.Line(point1=(49, 6),point2=(49, 5))
s.Line(point1=(49, 5),point2=(50, 4))
s.Line(point1=(50, 4),point2=(50, 3))
s.Line(point1=(50, 3),point2=(50, 2))
s.Line(point1=(50, 2),point2=(50, 1))
s.Line(point1=(50, 1),point2=(49, 1))
s.Line(point1=(49, 1),point2=(48, 1))
s.Line(point1=(48, 1),point2=(48, 2))
s.Line(point1=(48, 2),point2=(48, 3))
s.Line(point1=(48, 3),point2=(47, 4))
s.Line(point1=(47, 4),point2=(46, 4))
s.Line(point1=(46, 4),point2=(46, 5))
s.Line(point1=(46, 5),point2=(45, 6))
s.Line(point1=(45, 6),point2=(44, 6))
s.Line(point1=(44, 6),point2=(44, 7))
s.Line(point1=(44, 7),point2=(43, 8))
s.Line(point1=(43, 8),point2=(42, 9))
s.Line(point1=(42, 9),point2=(41, 9))
s.Line(point1=(41, 9),point2=(40, 9))
s.Line(point1=(40, 9),point2=(40, 10))
s.Line(point1=(40, 10),point2=(39, 11))
s.Line(point1=(39, 11),point2=(38, 11))
s.Line(point1=(38, 11),point2=(37, 11))
s.Line(point1=(37, 11),point2=(36, 11))
s.Line(point1=(36, 11),point2=(35, 11))
s.Line(point1=(35, 11),point2=(34, 11))
s.Line(point1=(34, 11),point2=(33, 11))
s.Line(point1=(33, 11),point2=(32, 11))
s.Line(point1=(32, 11),point2=(31, 10))
s.Line(point1=(31, 10),point2=(31, 9))
s.Line(point1=(31, 9),point2=(31, 8))
s.Line(point1=(31, 8),point2=(30, 9))
s.Line(point1=(30, 9),point2=(29, 9))
s.Line(point1=(29, 9),point2=(28, 8))
s.Line(point1=(28, 8),point2=(28, 7))
s.Line(point1=(28, 7),point2=(28, 6))
s.Line(point1=(28, 6),point2=(27, 6))
s.Line(point1=(27, 6),point2=(26, 6))
s.Line(point1=(26, 6),point2=(25, 6))
s.Line(point1=(25, 6),point2=(24, 6))
s.Line(point1=(24, 6),point2=(23, 6))
s.Line(point1=(23, 6),point2=(23, 7))
s.Line(point1=(23, 7),point2=(23, 8))
s.Line(point1=(23, 8),point2=(22, 9))
s.Line(point1=(22, 9),point2=(21, 9))
s.Line(point1=(21, 9),point2=(20, 8))
s.Line(point1=(20, 8),point2=(20, 9))
s.Line(point1=(20, 9),point2=(20, 10))
s.Line(point1=(20, 10),point2=(19, 11))
s.Line(point1=(19, 11),point2=(18, 11))
s.Line(point1=(18, 11),point2=(17, 11))
s.Line(point1=(17, 11),point2=(16, 11))
s.Line(point1=(16, 11),point2=(15, 11))
s.Line(point1=(15, 11),point2=(14, 11))
s.Line(point1=(14, 11),point2=(13, 11))
s.Line(point1=(13, 11),point2=(12, 11))
s.Line(point1=(12, 11),point2=(11, 10))
s.Line(point1=(11, 10),point2=(11, 9))
s.Line(point1=(11, 9),point2=(10, 9))
s.Line(point1=(10, 9),point2=(9, 9))
s.Line(point1=(9, 9),point2=(8, 8))
s.Line(point1=(8, 8),point2=(7, 7))
s.Line(point1=(7, 7),point2=(7, 6))
s.Line(point1=(7, 6),point2=(6, 6))
s.Line(point1=(6, 6),point2=(5, 5))
s.Line(point1=(5, 5),point2=(5, 4))
s.Line(point1=(5, 4),point2=(4, 4))
s.Line(point1=(4, 4),point2=(3, 3))
s.Line(point1=(3, 3),point2=(3, 2))
s.Line(point1=(3, 2),point2=(3, 1))
s.Line(point1=(3, 1),point2=(2, 1))
s.Line(point1=(2, 1),point2=(1, 1))
p = mdb.models["Model-1"].Part(name="S20_009", dimensionality=TWO_D_PLANAR,type=DEFORMABLE_BODY)
p = mdb.models["Model-1"].parts["S20_009"]
p.BaseShell(sketch=s)
s.unsetPrimaryObject()
p = mdb.models["Model-1"].parts["S20_009"]
session.viewports["Viewport: 1"].setValues(displayedObject=p)
del mdb.models["Model-1"].sketches["__profile__"]
session.viewports["Viewport: 1"].partDisplay.setValues(mesh=ON)
session.viewports["Viewport: 1"].partDisplay.meshOptions.setValues(meshTechnique=ON)
session.viewports["Viewport: 1"].partDisplay.geometryOptions.setValues(
referenceRepresentation=OFF)
p = mdb.models["Model-1"].parts["S20_009"]
p.seedPart(size=10, deviationFactor=0.1, minSizeFactor=0.1)
p = mdb.models["Model-1"].parts["S20_009"]
p.generateMesh()
s=p.edges
edges=s.findAt(((1, 1, 0),),((1, 2, 0),),((1, 3, 0),),((1, 4, 0),),((2, 5, 0),),((2, 6, 0),),((2, 7, 0),),((2, 8, 0),),((1, 9, 0),),((1, 10, 0),),((1, 11, 0),),((1, 12, 0),),((1, 13, 0),),((1, 14, 0),),((1, 15, 0),),((1, 16, 0),),((1, 17, 0),),((1, 18, 0),),((1, 19, 0),),((1, 20, 0),),((1, 21, 0),),((1, 22, 0),),((1, 23, 0),),((1, 24, 0),),((1, 25, 0),),((1, 26, 0),),((1, 27, 0),),((1, 28, 0),),((1, 29, 0),),((1, 30, 0),),((1, 31, 0),),((1, 32, 0),),((1, 33, 0),),((1, 34, 0),),((1, 35, 0),),((1, 36, 0),),((1, 37, 0),),((1, 38, 0),),((1, 39, 0),),((1, 40, 0),),((1, 41, 0),),((1, 42, 0),),((2, 43, 0),),((2, 44, 0),),((2, 45, 0),),((2, 46, 0),),((1, 47, 0),),((1, 48, 0),),((1, 49, 0),),((1, 50, 0),),)
p.Surface(side1Edges=edges, name="left")
edges=s.findAt(((49, 1, 0),),((48, 1, 0),),((48, 2, 0),),((48, 3, 0),),((47, 4, 0),),((46, 4, 0),),((46, 5, 0),),((45, 6, 0),),((44, 6, 0),),((44, 7, 0),),((43, 8, 0),),((42, 9, 0),),((41, 9, 0),),((40, 9, 0),),((40, 10, 0),),((39, 11, 0),),((38, 11, 0),),((37, 11, 0),),((36, 11, 0),),((35, 11, 0),),((34, 11, 0),),((33, 11, 0),),((32, 11, 0),),((31, 10, 0),),((31, 9, 0),),((31, 8, 0),),((30, 9, 0),),((29, 9, 0),),((28, 8, 0),),((28, 7, 0),),((28, 6, 0),),((27, 6, 0),),((26, 6, 0),),((25, 6, 0),),((24, 6, 0),),((23, 6, 0),),((23, 7, 0),),((23, 8, 0),),((22, 9, 0),),((21, 9, 0),),((20, 8, 0),),((20, 9, 0),),((20, 10, 0),),((19, 11, 0),),((18, 11, 0),),((17, 11, 0),),((16, 11, 0),),((15, 11, 0),),((14, 11, 0),),((13, 11, 0),),((12, 11, 0),),((11, 10, 0),),((11, 9, 0),),((10, 9, 0),),((9, 9, 0),),((8, 8, 0),),((7, 7, 0),),((7, 6, 0),),((6, 6, 0),),((5, 5, 0),),((5, 4, 0),),((4, 4, 0),),((3, 3, 0),),((3, 2, 0),),((3, 1, 0),),((2, 1, 0),),((1.5, 1, 0),),)
p.Surface(side1Edges=edges, name="bottom")
edges=s.findAt(((2, 50, 0),),((3, 50, 0),),((3, 49, 0),),((3, 48, 0),),((4, 47, 0),),((5, 47, 0),),((5, 46, 0),),((6, 45, 0),),((7, 45, 0),),((7, 44, 0),),((8, 43, 0),),((9, 42, 0),),((10, 42, 0),),((11, 42, 0),),((11, 41, 0),),((12, 40, 0),),((13, 40, 0),),((14, 40, 0),),((15, 40, 0),),((16, 40, 0),),((17, 40, 0),),((18, 40, 0),),((19, 40, 0),),((20, 41, 0),),((20, 42, 0),),((20, 43, 0),),((21, 42, 0),),((22, 42, 0),),((23, 43, 0),),((23, 44, 0),),((23, 45, 0),),((24, 45, 0),),((25, 45, 0),),((26, 45, 0),),((27, 45, 0),),((28, 45, 0),),((28, 44, 0),),((28, 43, 0),),((29, 42, 0),),((30, 42, 0),),((31, 43, 0),),((31, 42, 0),),((31, 41, 0),),((32, 40, 0),),((33, 40, 0),),((34, 40, 0),),((35, 40, 0),),((36, 40, 0),),((37, 40, 0),),((38, 40, 0),),((39, 40, 0),),((40, 41, 0),),((40, 42, 0),),((41, 42, 0),),((42, 42, 0),),((43, 43, 0),),((44, 44, 0),),((44, 45, 0),),((45, 45, 0),),((46, 46, 0),),((46, 47, 0),),((47, 47, 0),),((48, 48, 0),),((48, 49, 0),),((48, 50, 0),),((49, 50, 0),),((50, 50, 0),),)
p.Surface(side1Edges=edges, name="top")
edges=s.findAt(((50, 49, 0),),((50, 48, 0),),((50, 47, 0),),((49, 46, 0),),((49, 45, 0),),((49, 44, 0),),((49, 43, 0),),((50, 42, 0),),((50, 41, 0),),((50, 40, 0),),((50, 39, 0),),((50, 38, 0),),((50, 37, 0),),((50, 36, 0),),((50, 35, 0),),((50, 34, 0),),((50, 33, 0),),((50, 32, 0),),((50, 31, 0),),((50, 30, 0),),((50, 29, 0),),((50, 28, 0),),((50, 27, 0),),((50, 26, 0),),((50, 25, 0),),((50, 24, 0),),((50, 23, 0),),((50, 22, 0),),((50, 21, 0),),((50, 20, 0),),((50, 19, 0),),((50, 18, 0),),((50, 17, 0),),((50, 16, 0),),((50, 15, 0),),((50, 14, 0),),((50, 13, 0),),((50, 12, 0),),((50, 11, 0),),((50, 10, 0),),((50, 9, 0),),((49, 8, 0),),((49, 7, 0),),((49, 6, 0),),((49, 5, 0),),((50, 4, 0),),((50, 3, 0),),((50, 2, 0),),((50, 1, 0),),)
p.Surface(side1Edges=edges, name="right")
mdb.models["Model-1"].Material(name="Material-1")
mdb.models["Model-1"].materials["Material-1"].Elastic(table=((1E6, 0.3), ))
mdb.models["Model-1"].HomogeneousSolidSection(name="S20_009",
material="Material-1", thickness=None)
f = p.faces
faces= p.faces.findAt(((1,1,0), (50,50,0)), )
region = p.Set(faces=faces, name="S20_009")
p = mdb.models["Model-1"].parts["S20_009"]
p.SectionAssignment(region=region, sectionName="S20_009", offset=0.0,
offsetType=MIDDLE_SURFACE, offsetField="",
thicknessAssignment=FROM_SECTION)